To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your local device, follow [our guide](https://unsloth.ai/docs/get-started/install). This notebook is licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & how to save it

### News

Introducing **[Unsloth Desktop](https://unsloth.ai/docs/desktop)**, the first desktop app to run and train models. Free and open-source for macOS, Windows and Linux. [GitHub](https://github.com/unslothai/unsloth) • [Download](https://unsloth.ai/download)

<p>
<a href="https://unsloth.ai/docs/desktop"><img src="https://raw.githubusercontent.com/unslothai/notebooks/refs/heads/main/assets/unsloth-qwen3-8.png" width="350" alt="Introducing Unsloth Desktop"></a>
</p>

Train MoEs - DeepSeek, GLM, Qwen and gpt-oss 12x faster with 35% less VRAM. [Blog](https://unsloth.ai/docs/new/faster-moe)

Ultra Long-Context Reinforcement Learning is here with 7x more context windows! [Blog](https://unsloth.ai/docs/new/grpo-long-context)

New in Reinforcement Learning: [FP8 RL](https://unsloth.ai/docs/new/fp8-reinforcement-learning) • [Vision RL](https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl) • [Standby](https://unsloth.ai/docs/basics/memory-efficient-rl) • [gpt-oss RL](https://unsloth.ai/docs/new/gpt-oss-reinforcement-learning)

Visit our docs for all our [model uploads](https://unsloth.ai/docs/get-started/unsloth-model-catalog) and [notebooks](https://unsloth.ai/docs/get-started/unsloth-notebooks).

### Installation

In [1]:
%%capture
import os
os.environ["UNSLOTH_VLLM_STANDBY"] = "1" # [NEW] Extra 30% context lengths!
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install or uv pip install
    !pip install unsloth vllm
else:
    pass # For Colab / Kaggle, we need extra instructions hidden below \/

In [2]:
#@title Colab Extra Install { display-mode: "form" }
%%capture
import os
!pip install --upgrade -qqq uv
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install!
    !pip install unsloth vllm
else:
    try: import numpy, PIL; _numpy = f'numpy=={numpy.__version__}'; _pil = f'pillow=={PIL.__version__}'
    except: _numpy = "numpy"; _pil = "pillow"
    try: import subprocess; is_t4 = "Tesla T4" in str(subprocess.check_output(["nvidia-smi"]))
    except: is_t4 = False
    _vllm, _triton = ('vllm==0.11.2', 'triton') if is_t4 else ('vllm==0.15.1', 'triton')
    !uv pip install -qqq --upgrade {_vllm} {_numpy} {_pil} torchvision bitsandbytes xformers unsloth
    !uv pip install -qqq {_triton}
    try:
        import importlib.metadata as _md; _torch_v = tuple(int(_p) for _p in _md.version("torch").split("+")[0].split(".")[:2])
    except Exception:
        _torch_v = ()
    # torchao 0.18.0 imports torch.nn.functional.ScalingType, added in torch 2.10; peft >= 0.19 needs the 0.16.0 floor.
    _torchao = "torchao>=0.16.0" if _torch_v >= (2, 10) else "torchao>=0.16.0,<0.18.0"
    !uv pip install -qqq --no-deps --upgrade "{_torchao}"
!uv pip install transformers==4.56.2
!uv pip install --no-deps trl==0.22.2

### Unsloth

Goal: To convert `DeepSeek-R1-0528-Qwen3-8B` into a reasoning model via GRPO by using OpenR1's Math dataset.

We also use `langid` for language detection. Our main goal is to force the model to generate reasoning traces in Indonesian, and we create a reward function using `langid` to check this.

In [3]:
!pip install langid -qq

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 4.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for langid (setup.py) ... done

In [4]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 1024 # Can increase for longer reasoning traces
lora_rank = 32 # Larger rank = smarter, but slower

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/DeepSeek-R1-0528-Qwen3-8B",
    max_seq_length = max_seq_length,
    load_in_4bit = True, # False for LoRA 16bit
    fast_inference = True, # Enable vllm fast inference
    max_lora_rank = lora_rank,
    gpu_memory_utilization = 0.9, # Reduce if out of memory
)

model = FastLanguageModel.get_peft_model(
    model,
    r = lora_rank, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha = lora_rank*2, # *2 speeds up training
    use_gradient_checkpointing = "unsloth", # Reduces memory usage
    random_state = 3407,
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/usr/local/lib/python3.13/dist-packages/unsloth/_gpu_init.py:304: UserWarning: torchcodec 0.11.0+cu128 is incompatible with torch 2.9.0+cu128; install a matching build with `pip install --index-url https://download.pytorch.org/whl/cu128 'torchcodec>=0.9,<0.10.0'`.
  disable_torchcodec_if_broken()

ERROR 09-11 07:44:58 [fa_utils.py:64] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
🦥 Unsloth Zoo will now patch everything to make training faster!

Unrecognized keys in `rope_scaling` for 'rope_type'='yarn': {'attn_factor'}

INFO 09-11 07:45:33 [vllm_utils.py:752] Unsloth: Patching vLLM v1 graph capture
==((====))==  Unsloth 2026.9.4: Fast Qwen3 patching. Transformers: 4.56.2. vLLM: 0.11.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unrecognized keys in `rope_scaling` for 'rope_type'='yarn': {'attn_factor'}

Unsloth: Not planning a device map; vLLM places its own weights. Using `sequential`.
Unsloth: Standby mode is enabled. However your setting of `gpu_memory_utilization` will OOM.
Changing `gpu_memory_utilization` to 0.76.
Unsloth: vLLM loading unsloth/deepseek-r1-0528-qwen3-8b-unsloth-bnb-4bit with actual GPU utilization = 75.26%
Unsloth: Your GPU has CUDA compute capability 7.5 with VRAM = 14.56 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 1024. Num Sequences = 32.
Unsloth: vLLM's KV Cache can use up to 4.29 GB. Also swap space = 0 GB.
Unsloth: Not an error, but `use_cudagraph` is not supported in vLLM.config.CompilationConfig. Skipping.
WARNING 09-11 07:46:39 [compilation.py:610] Level is deprecated and will be removed in the next release,either 0.12.0 or 0.11.2 whichever is soonest.Use mode instead.If both level and mode are given,only mode will be used.
WARNING 09-11 07:46:39 [compilation.py:699] The 'use_inductor' flag is deprecated and will be removed in the next release (v0.12.0). Please use the 'backend' option instead.
Unsloth: Not an error, but `device` is not supported in vLLM. Skipping.
INFO 09-11 07:46:39 [utils.py:253] non-default args: {'load_format': 'bitsandbytes', 'dtype': torch.float16, 'seed': 0, 'max_model_len': 1024, 'enable_prefix_caching': True, 'swap_space': 0, 'gpu_memory_utilization': 0.7526166896476574, 'max_num_batched_tokens': 4096, 'max_num_seqs': 32, 'max_logprobs': 0, 'disable_log_stats': True, 'quantization': 'bitsandbytes', 'enable_lora': True, 'max_lora_rank': 32, 'enable_chunked_prefill': True, 'compilation_config': {'level': 3, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': [], 'splitting_ops': None, 'compile_mm_encoder': False, 'use_inductor': True, 'compile_sizes': None, 'inductor_compile_config': {'epilogue_fusion': True, 'max_autotune': False, 'shape_padding': True, 'trace.enabled': False, 'triton.cudagraphs': False, 'debug': False, 'dce': True, 'memory_planning': True, 'coordinate_descent_tuning': False, 'trace.graph_diagram': False, 'compile_threads': 4, 'group_fusion': True, 'disable_progress': False, 'verbose_progress': True, 'triton.multi_kernel': 0, 'triton.use_block_ptr': True, 'triton.enable_persistent_tma_matmul': True, 'triton.autotune_at_compile_time': False, 'triton.cooperative_reductions': False, 'cuda.compile_opt_level': '-O2', 'cuda.enable_cuda_lto': True, 'combo_kernels': False, 'benchmark_combo_kernel': True, 'combo_kernel_foreach_dynamic_shapes': True, 'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_cudagraph_capture_size': None, 'local_cache_dir': None}, 'enable_sleep_mode': True, 'model': 'unsloth/deepseek-r1-0528-qwen3-8b-unsloth-bnb-4bit'}

/usr/local/lib/python3.13/dist-packages/pydantic/type_adapter.py:607: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `enum` - serialized value may not be as expected [field_name='mode', input_value=3, input_type=int])
  return self.serializer.to_python(
Unrecognized keys in `rope_scaling` for 'rope_type'='yarn': {'attn_factor'}

INFO 09-11 07:46:55 [model.py:631] Resolved architecture: Qwen3ForCausalLM
WARNING 09-11 07:46:55 [model.py:1971] Casting torch.bfloat16 to torch.float16.
INFO 09-11 07:46:55 [model.py:1745] Using max model len 1024
INFO 09-11 07:46:57 [scheduler.py:216] Chunked prefill is enabled with max_num_batched_tokens=4096.
Unsloth: vLLM Bitsandbytes config using kwargs = {'load_in_8bit': False, 'load_in_4bit': True, 'bnb_4bit_compute_dtype': 'float16', 'bnb_4bit_quant_storage': 'uint8', 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': True, 'llm_int8_enable_fp32_cpu_offload': False, 'llm_int8_has_fp16_weight': False, 'llm_int8_skip_modules': ['lm_head', 'multi_modal_projector', 'merger', 'modality_projection', 'model.layers.33.self_attn', 'model.layers.34.self_attn', 'model.layers.1.self_attn', 'model.layers.6.self_attn', 'model.layers.34.mlp', 'model.layers.4.mlp', 'model.layers.2.mlp', 'model.layers.5.mlp', 'model.layers.6.mlp'], 'llm_int8_threshold': 6.0}

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/472 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/171 [00:00<?, ?B/s]

INFO 09-11 07:47:03 [core.py:93] Initializing a V1 LLM engine (v0.11.2) with config: model='unsloth/deepseek-r1-0528-qwen3-8b-unsloth-bnb-4bit', speculative_config=None, tokenizer='unsloth/deepseek-r1-0528-qwen3-8b-unsloth-bnb-4bit', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=1024, download_dir=None, load_format=bitsandbytes, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/deepseek-r1-0528-qwen3-8b-unsloth-bnb-4bit, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': 3, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer'], 'compile_mm_encoder': False, 'use_inductor': True, 'compile_sizes': [], 'inductor_compile_config': {'epilogue_fusion': True, 'max_autotune': False, 'shape_padding': True, 'trace.enabled': False, 'triton.cudagraphs': False, 'debug': False, 'dce': True, 'memory_planning': True, 'coordinate_descent_tuning': False, 'trace.graph_diagram': False, 'compile_threads': 4, 'group_fusion': True, 'disable_progress': False, 'verbose_progress': True, 'triton.multi_kernel': 0, 'triton.use_block_ptr': True, 'triton.enable_persistent_tma_matmul': True, 'triton.autotune_at_compile_time': False, 'triton.cooperative_reductions': False, 'cuda.compile_opt_level': '-O2', 'cuda.enable_cuda_lto': True, 'combo_kernels': False, 'benchmark_combo_kernel': True, 'combo_kernel_foreach_dynamic_shapes': True, 'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_cudagraph_capture_size': 64, 'local_cache_dir': None}
INFO 09-11 07:47:03 [parallel_state.py:1208] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:42597 backend=nccl
INFO 09-11 07:47:03 [parallel_state.py:1394] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0

/usr/local/lib/python3.13/dist-packages/pydantic/type_adapter.py:607: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `enum` - serialized value may not be as expected [field_name='mode', input_value=3, input_type=int])
  return self.serializer.to_python(

INFO 09-11 07:47:04 [topk_topp_sampler.py:36] Using FlashInfer for top-p & top-k sampling.
INFO 09-11 07:47:04 [gpu_model_runner.py:3259] Starting to load model unsloth/deepseek-r1-0528-qwen3-8b-unsloth-bnb-4bit...
INFO 09-11 07:47:05 [cuda.py:377] Using AttentionBackendEnum.FLASHINFER backend.
INFO 09-11 07:47:05 [bitsandbytes_loader.py:791] Loading weights with BitsAndBytes quantization. May take a while ...

model-00001-of-00002.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

INFO 09-11 07:48:51 [weight_utils.py:441] Time spent downloading weights for unsloth/deepseek-r1-0528-qwen3-8b-unsloth-bnb-4bit: 104.968321 seconds

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]

INFO 09-11 07:49:23 [punica_selector.py:20] Using PunicaWrapperGPU.
INFO 09-11 07:49:24 [gpu_model_runner.py:3338] Model loading took 7.1280 GiB memory and 138.308712 seconds
INFO 09-11 07:49:45 [backends.py:631] Using cache directory: /root/.cache/vllm/torch_compile_cache/cf55a39dc5/rank_0_0/backbone for vLLM's torch.compile
INFO 09-11 07:49:45 [backends.py:647] Dynamo bytecode transform time: 20.17 s

Unsloth: Compiling kernels: 100%|██████████| 3/3 [00:03<00:00,  1.07s/it, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_4]

INFO 09-11 07:49:59 [backends.py:251] Cache the graph for dynamic shape for later use

Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:01<00:00,  4.52it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 196.85it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 203.37it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 178.08it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 156.98it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 189.34it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 160.10it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 215.05it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 223.66it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 193.52it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 218.97it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 206.16it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 225.80it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 212.39it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 217.21it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 210.18it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 211.78it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 206.18it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 202.27it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 171.94it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 197.92it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 172.89it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 204.74it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 194.97it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 163.62it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 137.91it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 211.36it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 178.28it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 182.99it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 210.35it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 233.16it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 199.62it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 225.67it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 167.93it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 218.22it/s, triton_poi_fused__to_copy_add_index_select_mean_mul_pow_rsqrt_split_split_with_sizes_sub_unsqueeze_view_6]
Unsloth: Compiling kernels: 100%|██████████| 3/3 [00:00<00:00, 12.94it/s, triton_red_fused__to_copy_add_mean_mul_pow_rsqrt_2]

INFO 09-11 07:50:41 [backends.py:282] Compiling a graph for dynamic shape takes 53.49 s

INFO 09-11 07:51:05 [monitor.py:34] torch.compile takes 73.66 s in total
INFO 09-11 07:52:59 [gpu_worker.py:359] Available KV cache memory: 3.23 GiB
INFO 09-11 07:53:00 [kv_cache_utils.py:1229] GPU KV cache size: 23,520 tokens
INFO 09-11 07:53:00 [kv_cache_utils.py:1234] Maximum concurrency for 1,024 tokens per request: 22.97x
INFO 09-11 07:53:00 [kernel_warmup.py:65] Warming up FlashInfer attention.
INFO 09-11 07:55:51 [vllm_utils.py:757] Unsloth: Running patched vLLM v1 `capture_model`.

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE):   0%|          | 0/22 [00:00<?, ?it/s]

WARNING 09-11 07:55:51 [utils.py:250] Using default LoRA kernel configs

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 22/22 [00:42<00:00,  1.94s/it]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 14/14 [00:03<00:00,  4.26it/s]

INFO 09-11 07:56:37 [gpu_model_runner.py:4244] Graph capturing finished in 46 secs, took 0.52 GiB
INFO 09-11 07:56:37 [vllm_utils.py:764] Unsloth: Patched vLLM v1 graph capture finished in 46 secs.

INFO 09-11 07:56:39 [core.py:250] init engine (profile, create kv cache, warmup model) took 434.77 seconds
INFO 09-11 07:56:42 [llm.py:352] Supported tasks: ('generate',)

`torch_dtype` is deprecated! Use `dtype` instead!

Unsloth: Just some info: will skip parsing ['q_norm', 'post_per_layer_input_norm', 'norm2', 'ffn_norm', 'norm1', 'layer_norm1', 'layer_norm2', 'norm', 'post_feedforward_layernorm', 'input_layernorm', 'pre_feedforward_layernorm', 'post_layernorm', 'attention_norm', 'k_norm', 'post_attention_layernorm']

Unrecognized keys in `rope_scaling` for 'rope_type'='yarn': {'attn_factor'}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Performing substitution for additional_keys=set()
Unsloth: Just some info: will skip parsing ['cross_attn_post_attention_layernorm', 'q_norm', 'post_per_layer_input_norm', 'norm2', 'ffn_norm', 'norm1', 'layer_norm1', 'layer_norm2', 'norm', 'post_feedforward_layernorm', 'input_layernorm', 'pre_feedforward_layernorm', 'post_layernorm', 'cross_attn_input_layernorm', 'attention_norm', 'k_norm', 'post_attention_layernorm']

Unsloth 2026.9.4 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

### GRPO Chat Template

Distill Qwen3 from Deepseek has a chat template that is used to format the input and output of the model. This is used to make the model output in a chat format. Including the reasoning step. We have to use that chat template since the model is trained using it.

Let's see how our chat template behaves on an example:

In [5]:
reasoning_start = None
reasoning_end = None
user_token = None
assistant_token = None

for token in tokenizer.get_added_vocab().keys():
    if "think" in token and "/" in token:
        reasoning_end = token
    elif "think" in token:
        reasoning_start = token
    elif "user" in token:
        user_token = token
    elif "assistant" in token:
        assistant_token = token

system_prompt = \
f"""You are given a problem.
Think about the problem and provide your working out.
You must think in Bahasa Indonesia."""
system_prompt

'You are given a problem.\nThink about the problem and provide your working out.\nYou must think in Bahasa Indonesia.'

In [6]:
print(tokenizer.apply_chat_template([
    {"role" : "user", "content" : "What is 1+1?"},
    {"role" : "assistant", "content" : f"<think>I think it's 2.2</think>2"},
    {"role" : "user", "content" : "What is 1+1?"},
    {"role" : "assistant", "content" : f"<think>I think it's 2.2</think>2"},
], tokenize = False, add_generation_prompt = True))

<｜begin▁of▁sentence｜><｜User｜>What is 1+1?<｜Assistant｜>2<｜end▁of▁sentence｜><｜User｜>What is 1+1?<｜Assistant｜>2<｜end▁of▁sentence｜><｜Assistant｜>

### Data Prep
<a name="Data"></a>

We're using Hugging Face's [Open R1 Math dataset](https://huggingface.co/datasets/open-r1/DAPO-Math-17k-Processed). You can also utilize OpenAI's famous [GSM8K dataset](https://huggingface.co/datasets/openai/gsm8k)

In [7]:
from datasets import load_dataset
dataset =  load_dataset("openai/gsm8k", "main", split="train")
dataset

README.md: 0.00B [00:00, ?B/s]

main/train-00000-of-00001.parquet:   0%|          | 0.00/2.31M [00:00<?, ?B/s]

main/test-00000-of-00001.parquet:   0%|          | 0.00/419k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/7473 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1319 [00:00<?, ? examples/s]

Dataset({
    features: ['question', 'answer'],
    num_rows: 7473
})

In [8]:
dataset = dataset.rename_column("question", "prompt")
dataset = dataset.rename_column("answer", "solution")

Let's look at the first row:

In [9]:
dataset[0]["prompt"]

'Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?'

In [10]:
dataset[0]["solution"]

'Natalia sold 48/2 = <<48/2=24>>24 clips in May.\nNatalia sold 48+24 = <<48+24=72>>72 clips altogether in April and May.\n#### 72'

In GSM8K, we notice all answers like about have a ####, so we extract it. But for the Open R1 dataset, we can skip the below.

In [11]:
def extract_hash_answer(text):
    if "####" not in text: return None
    return text.split("####")[1].strip()
    # return text
extract_hash_answer(dataset[0]["solution"])

'72'

Let's map the dataset! and see the first row:

In [12]:
dataset = dataset.map(lambda x: {
    "prompt" : [
        {"role": "system", "content": system_prompt},
        {"role": "user",   "content": x["prompt"]},
    ],
    "answer": extract_hash_answer(x["solution"]),
})
dataset[0]

Map:   0%|          | 0/7473 [00:00<?, ? examples/s]

{'prompt': [{'role': 'system',
   'content': 'You are given a problem.\nThink about the problem and provide your working out.\nYou must think in Bahasa Indonesia.'},
  {'role': 'user',
   'content': 'Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?'}],
 'solution': 'Natalia sold 48/2 = <<48/2=24>>24 clips in May.\nNatalia sold 48+24 = <<48+24=72>>72 clips altogether in April and May.\n#### 72',
 'answer': '72'}

We create a regex format to match the reasoning sections and answers:

In [13]:
import re

# Add optional EOS token matching
solution_end_regex = rf"{reasoning_end}(.*)"

match_format = re.compile(solution_end_regex, re.DOTALL)
match_format

AttributeError: module 're' has no attribute 'TEMPLATE'

We verify it works:

In [14]:
match_format.findall(
    "Let me think!</think>"\
    f"Hence, the solution is 2.",
)

['Hence, the solution is 2.']

In [15]:
match_format.findall(
    "<think>Let me think!</think>"\
    f"\n\nHence, the solution is 2",
)

['\n\nHence, the solution is 2']

We now want to create a reward function to match the format exactly - we reward it with 3 points if it succeeds:

In [16]:
def match_format_exactly(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        # Match if format is seen exactly!
        if match_format.search(response) is not None: score += 3.0
        scores.append(score)
    return scores

If it fails, we want to reward the model if it at least follows the format partially, by counting each symbol:

In [17]:
def match_format_approximately(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        # Count how many keywords are seen - we penalize if too many!
        # If we see 1, then plus some points!

        # No need to reward the think tag since we always prepend it!
        score += 0.5 if response.count(reasoning_start) == 1 else -1.0
        score += 0.5 if response.count(reasoning_end)   == 1 else -1.0
        scores.append(score)
    return scores

We want to extract the generated answer, and reward or penalize it! We also reward it based on how close the answer is to the true one via ratios:

In [18]:
def check_answer(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = [
        guess.group(1)
        if (guess := match_format.search(r)) is not None else None \
        for r in responses
    ]

    scores = []
    for guess, true_answer in zip(extracted_responses, answer):
        score = 0
        if guess is None:
            scores.append(-2.0)
            continue
        # Correct answer gets 5 points!
        if guess == true_answer:
            score += 5.0
        # Match if spaces are seen, but less reward
        elif guess.strip() == true_answer.strip():
            score += 3.5
        else:
            # We also reward it if the answer is close via ratios!
            # Ie if the answer is within some range, reward it!
            try:
                ratio = float(guess) / float(true_answer)
                if   ratio >= 0.9 and ratio <= 1.1: score += 2.0
                elif ratio >= 0.8 and ratio <= 1.2: score += 1.5
                else: score -= 2.5 # Penalize wrong answers
            except:
                score -= 4.5 # Penalize
        scores.append(score)
    return scores

Also sometimes it might not be 1 number as the answer, but like a sentence for example "The solution is $20" -> we extract 20.

We also remove possible commas for example as in 123,456

In [19]:
match_numbers = re.compile(
    r".*?[\s]{0,}([-]?[\d\.\,]{1,})",
    flags = re.MULTILINE | re.DOTALL
)
print(match_numbers.findall("  0.34  "))
print(match_numbers.findall("  123,456  "))
print(match_numbers.findall("  -0.234  "))
print(match_numbers.findall("17"))

['0.34']
['123,456']
['-0.234']
['17']

Finally, we will try to enforce the thinking process to be in Bahasa Indonesia. This is a simple version of the `language consistency reward` that is used in DeepSeek R1 paper

In [20]:
import langid

def get_lang(text: str) -> str:
    if not text:
        return "und"
    lang, _ = langid.classify(text)
    return lang


print(get_lang("Hello, How are you")) # This should return en
print(get_lang("Aku berpikir kalau aku adalah kamu")) # This should return id
print(get_lang("我在这里")) # This should return zh

en
id
zh

In [21]:
import re

def format_and_language_reward_func(completions, **kwargs):
    scores = []

    for completion_item in completions:
        if not completion_item or not isinstance(completion_item[0], dict) or "content" not in completion_item[0]:
            scores.append(-5.0)
            print(f"Warning: Malformed completion item, assigning default low score: {completion_item}")
            continue

        content = completion_item[0]["content"]

        lang = get_lang(content)

        if lang == 'id':
            score = 5.0
        elif lang == 'en':
            score = -3.0
        elif lang == 'zh':
            score = -3.0
        else:
            score = -5.0

        scores.append(score)

    return scores

In [22]:
prompts = [
    [{"role": "assistant", "content": "What is the result of (1 + 2) * 4?"}],
    [{"role": "assistant", "content": "What is the result of (3 + 1) * 2?"}],
]
completions = [
    [{"role": "assistant", "content": "<think>The sum of 1 and 2 is 3, which we multiply by 4 to get 12.</think><answer>(1 + 2) * 4 = 12</answer>"}],
    [{"role": "assistant", "content": "The sum of 3 and 1 is 4, which we multiply by 2 to get 8. So (3 + 1) * 2 = 8."}],
]
format_and_language_reward_func(prompts = prompts, completions = completions)

[-3.0, -3.0]

We now prepare our main function which will print out the generated responses and the true answer, along with another reward function which converts text to float via `float` and sees if it's the same.

In [23]:
global PRINTED_TIMES
PRINTED_TIMES = 0
global PRINT_EVERY_STEPS
PRINT_EVERY_STEPS = 5

def check_numbers(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = [
        guess.group(1)
        if (guess := match_numbers.search(r)) is not None else None \
        for r in responses
    ]

    scores = []
    # Print only every few steps
    global PRINTED_TIMES
    global PRINT_EVERY_STEPS
    if PRINTED_TIMES % PRINT_EVERY_STEPS == 0:
        print(
            '*'*20 + f"Question:\n{question}", f"\nAnswer:\n{answer[0]}", f"\nResponse:\n{responses[0]}", f"\nExtracted:\n{extracted_responses[0]}"
        )
    PRINTED_TIMES += 1

    for guess, true_answer in zip(extracted_responses, answer):
        if guess is None:
            scores.append(-2.5)
            continue
        # Convert to numbers
        try:
            true_answer = float(true_answer.strip())
            # Remove commas like in 123,456
            guess       = float(guess.strip().replace(",", ""))
            scores.append(3.5 if guess == true_answer else -1.5)
        except:
            scores.append(0)
            continue
    return scores

Get the top 90% prompt length so we don't accidentally truncate them!

Ie we'll remove the top 10% long prompts.

In [24]:
tokenized = dataset.map(
    lambda x: {"tokens" : tokenizer.apply_chat_template(x["prompt"], add_generation_prompt = True, tokenize = True)},
    batched = True,
)
print(tokenizer.decode(tokenized[0]["tokens"]))
tokenized = tokenized.map(lambda x: {"L" : len(x["tokens"])})

import numpy as np
maximum_length = int(np.quantile(tokenized["L"], 0.9))
print("Max Length = ", maximum_length)

# Filter only samples smaller than 90% max length
dataset = dataset.select(np.where(np.array(tokenized["L"]) <= maximum_length)[0])
del tokenized

Map:   0%|          | 0/7473 [00:00<?, ? examples/s]

<｜begin▁of▁sentence｜>You are given a problem.
Think about the problem and provide your working out.
You must think in Bahasa Indonesia.<｜User｜>Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?<｜Assistant｜>

Map:   0%|          | 0/7473 [00:00<?, ? examples/s]

Max Length =  116

<a name="Train"></a>
### Train the model

Now set up GRPO Trainer and all configurations!

In [25]:
max_prompt_length = maximum_length + 1 # + 1 just in case!
max_completion_length = max_seq_length - max_prompt_length

from vllm import SamplingParams
vllm_sampling_params = SamplingParams(
    min_p = 0.1,
    top_p = 1.0,
    top_k = -1,
    seed = 3407,
    stop = [tokenizer.eos_token],
    include_stop_str_in_output = True,
)

from trl import GRPOConfig, GRPOTrainer
training_args = GRPOConfig(
    vllm_sampling_params = vllm_sampling_params,
    temperature = 1.0,
    learning_rate = 5e-6,
    weight_decay = 0.001,
    warmup_ratio = 0.1,
    lr_scheduler_type = "linear",
    optim = "adamw_8bit",
    logging_steps = 1,
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 1, # Increase to 4 for smoother training
    num_generations = 4, # Decrease if out of memory
    max_prompt_length = max_prompt_length,
    max_completion_length = max_completion_length,
    # num_train_epochs = 1, # Set to 1 for a full training run
    max_steps = 100,
    save_steps = 100,
    report_to = "none", # Can use Weights & Biases
    output_dir = "outputs",

    # For optional training + evaluation
    # fp16_full_eval = True,
    # per_device_eval_batch_size = 4,
    # eval_accumulation_steps = 1,
    # eval_strategy = "steps",
    # eval_steps = 1,
)

Unsloth: We now expect `per_device_train_batch_size` * `gradient_accumulation_steps` * `world_size` to be a multiple of `num_generations`.
We will change the batch size of 1 to the `num_generations` of 4

And let's run the trainer! If you scroll up, you'll see a table of rewards. The goal is to see the `reward` column increase!

You might have to wait 150 to 200 steps for any action. You'll probably get 0 reward for the first 100 steps. Please be patient!

| Step | Training Loss | reward    | reward_std | completion_length | kl       |
|------|---------------|-----------|------------|-------------------|----------|
| 1    | 0.000000      | 0.125000  | 0.000000   | 200.000000        | 0.000000 |
| 2    | 0.000000      | 0.072375  | 0.248112   | 200.000000        | 0.000000 |
| 3    | 0.000000      | -0.079000 | 0.163776   | 182.500000        | 0.000005 |

In [26]:
# For optional training + evaluation
# new_dataset = dataset.train_test_split(test_size = 0.01)

trainer = GRPOTrainer(
    model = model,
    processing_class = tokenizer,
    reward_funcs = [
        match_format_exactly,
        match_format_approximately,
        check_answer,
        check_numbers,
        format_and_language_reward_func,
    ],
    args = training_args,
    train_dataset = dataset,

    # For optional training + evaluation
    # train_dataset = new_dataset["train"],
    # eval_dataset = new_dataset["test"],
)
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 6,749 | Num Epochs = 1 | Total steps = 100
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 1 x 1) = 4
 "-____-"     Trainable parameters = 87,293,952 of 8,278,029,312 (1.05% trained)

WARNING 09-11 07:57:24 [processor.py:246] vLLM has deprecated support for supporting different tokenizers for different LoRAs. By default, vLLM uses base model's tokenizer. If you are using a LoRA with its own tokenizer, consider specifying `--tokenizer [lora_path]` to use the LoRA tokenizer.
Unsloth: Will smartly offload gradients to save VRAM!
********************Question:
Jesse and Mia are competing in a week long race. They have one week to run 30 miles. On the first three days Jesse averages (2/3) of a mile. On day four she runs 10 miles. Mia averages 3 miles a day over the first 4 days. What is the average of their average that they have to run over the final three days?
Answer:
6
Response:
<think>
First, the problem is about a week-long race where Jesse and Mia are competing to run 30 miles in 7 days. I need to find the average of their averages for the final three days.

For Jesse:

- On the first three days, she averages (2/3) of a mile. But (2/3) of a mile per day? That seems too short. Let me read it again.

"On the first three days Jesse averages (2/3) of a mile."

Averages over three days, so (2/3) miles total for the first three days? Or per day? It says "averages (2/3) of a mile" – I think it means the average distance per day is (2/3) miles.

Similarly for Mia, "averages 3 miles a day over the first 4 days."

For Jesse: first three days, average (2/3) mile per day.

So, for three days, total distance: 3 days * (2/3) miles/day = 3 * 2/3 = 2 miles.

On day four, she runs 10 miles.

Now for Mia.

Mia averages 3 miles a day over the first 4 days.

So, first 4 days, average 3 miles per day, so total for first 4 days: 4 * 3 = 12 miles.

The race is 30 miles in 7 days.

For Jesse:

Total miles needed: 30.

First three days: 3 * (2/3) = 2 miles.

Day 4: 10 miles.

So, by day 4, Jesse has run 2 + 10 = 12 miles.

Now, final three days: days 5, 6, and 7.

Total for 7 days: 30 miles.

Jesse has ran 12 by day 4, so for final three days, she needs to run 30 - 12 = 18 miles.

But we need average, not total.

First, let's find her average for the final three days.

Distance to run: 18 miles in 3 days, so average per day: 18 / 3 = 6 miles/day.

Now for Mia.

Mia first 4 days: 12 miles.

Total needed: 30 miles.

So, in the last 3 days, she needs to run 30 - 12 = 18 miles as well.

Average per day: 18 / 3 = 6 miles/day.

Both have the same for the final three days: 6 miles per day average.

Now, the question is to find the average of their averages.

Jesse average for final three days: 6 miles/day.

Mia average for final three days: 6 miles/day.

Average of their averages: (6 + 6) / 2 = 12 / 2 = 6 miles/day.

But let's make sure.

The problem says "the average of their average" – so average of Jesse's average and Mia's average.

Both 6, so average is 6.

But is that the final answer?

Let me think again.

Jesse: first three days average (2/3) mile/day, but (2/3) is about 0.666 miles, so not much, then day four 10 miles, which is a lot, so the average for final three days is high.

Mia: first four days average 3 miles/day, not bad, and she needs to make up with final three days.

Both end up with 18 miles in last three days, so 6 miles/day average.

But let's confirm the dates.

Jesse runs first three days and day four is given separately.

Jesse: day 1,2,3: average (2/3) mile/day, so total 2 miles.

Day 4: 10 miles.

Then days 5,6,7: need to run 18 miles.

Similarly for Mia: first 4 days average 3 miles/day, so 12 miles in 4 days.

Then days 5,6,7: need 18 miles.

Yes.

Now, the average of their averages: Jesse's final average
Extracted:
,

Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.
********************Question:
Bill composes 20 total math questions for money.  Ryan composes twice as many problems as Bill, and Frank composes 3 times as many as Ryan.  Assuming each person has to compose 4 different types of math problems in equal proportion out of the total amount, how many problems of each type does Frank compose?
Answer:
30
Response:
<think>
First, the problem says Bill composes 20 total math questions. Ryan composes twice as many as Bill, so Ryan composes 2 * 20 = 40 questions. Frank composes three times as many as Ryan, so Frank composes 3 * 40 = 120 questions.

Now, each person has to compose 4 different types of math problems in equal proportion out of the total amount. So, for each person, the questions are divided equally among 4 types.

For Frank, he has 120 questions, divided into 4 equal types. So, each type has 120 / 4 = 30 questions.

The question is: how many problems of each type does Frank compose? So, it should be 30.

But let me make sure about the proportions. "in equal proportion out of the total amount" – I think it means that for each person, each type has the same number of questions, and that number is proportional or part of the total they compose.

Since it says "in equal proportion out of the total amount", it might refer to the total for each person.

Re-reading: "each person has to compose 4 different types of math problems in equal proportion out of the total amount"

"Out of the total amount" could be ambiguous. "The total amount" might refer to the total questions composed by that person, or by all together.

Let's read carefully.

"Bill composes 20 total math questions... Ryan twice as many, Frank three times as many Ryan."

Then, "each person has to compose 4 different types... in equal proportion out of the total amount"

"the total amount" – it might refer to the total questions that they themselves compose.

Because if it were the total for all, it might not make sense for equal proportion.

For example, Bill composes 20 total, divided into 4 types: each type has 20 / 4 = 5.

Ryan composes 40, each type 10.

Frank composes 120, each type 30.

But "out of the total amount" – if "total amount" means the total for all three, it would be different.

Total questions: Bill 20, Ryan 40, Frank 120, so total 20 + 40 + 120 = 180 questions.

Then, 4 different types for all, but the problem says "each person has to compose", so probably the types are defined per person or shared?

The way it's worded: "compose 4 different types of math problems"

And "in equal proportion" – proportion out of what?

Perhaps "the total amount" refers to the total questions composed by that individual.

I think that's more logical, because the types are probably different, but let's see.

Another interpretation: they compose the same 4 types, and each has equal proportion of each type.

But the problem doesn't say they have the same types, just that each has 4 types.

Let's read the sentence: "each person has to compose 4 different types of math problems in equal proportion out of the total amount"

"Total amount" likely means the total questions that they compose.

So, for each person, the 4 types are each composed in equal proportion out of their total composition.

So, for Bill, 20 total, 4 types, so 5 each.

Ryan, 40 total, 4 types, so 10 each.

Frank, 120 total, 4 types, so 30 each.

But the question is about Frank, so it should be 30.

But let's confirm if "the total amount" is shared or not.

Suppose "out of the total amount" means from the overall total.

But overall total is 180, divided by 4 types, each type has 45 questions.

Then, but this is for the types, not per person.

Each person would compose questions from these types, but the proportion might not be equal per person.

For example, if types are shared, each type has 45 questions.

Then, Frank composes 120 questions, but from which types? The proportion might be specified.

The problem doesn't say how the total amount
Extracted:
,
********************Question:
Macey saves to buy herself a shirt that costs $3. She was able to save $1.50 already. How many weeks does she need to save for the remaining amount if she saves $0.50 per week?
Answer:
3
Response:
<think>
Saya perlu menyelesaikan masalah matematika ini. Soalnya adalah Macey menabung untuk membeli pakaian yang harganya $3. Dia sudah menabung $1.50. Dia menabung $0.50 per minggu. Berapa minggu lagi dia perlu menabung untuk mencapai jumlah yang dibutuhkan?

Pertama, saya harus mencari berapa banyak uang yang masih dibutuhkan. Harga pakaian itu $3, dan dia sudah punya $1.50. Jadi, selisihnya adalah $3 - $1.50.

Hitung: 3.00 - 1.50 = 1.50. Jadi, dia masih membutuhkan $1.50 lagi.

Sekarang, dia menabung $0.50 per minggu. Jadi, saya perlu mencari berapa minggu yang dibutuhkan untuk menabung $1.50 dengan jatah $0.50 per minggu.

Itu seperti membagi 1.50 dengan 0.50.

Jadi, 1.50 ÷ 0.50.

Bagi 1.50 dengan 0.50 sama saja dengan mengalinya dengan kebalikan. 0.50 adalah setengah dari 1.00, tapi lebih mudah dengan pecahan.

1.50 / 0.50 = 150 / 50. Kenapa? Karena $1.50 dan $0.50 bisa dikalikan dengan 100 untuk jadi angka bulat: 150 dan 50.

150 / 50 = 3.

Jadi, 3 minggu.

Cara lain, jika dia menabung $0.50 per minggu, untuk menabung $1.50, dia perlu 1.50 ÷ 0.50 = 3.

Minggu ketiga, dia menabung $0.50, jadi total tabungannya menjadi 1.50 + 0.50 = 2.00, itu sudah lebih dari $2.00, tapi dia cuma butuh $3.00.

Jumlah yang dibutuhkan adalah $1.50 lagi.

Setelah 1 minggu: tabungan 1.50 + 0.50 = 2.00

Setelah 2 minggu: 2.00 + 0.50 = 2.50

Setelah 3 minggu: 2.50 + 0.50 = 3.00

Ya, setelah 3 minggu, dia mencapai $3.00.

Minggu pertama dia menabung $0.50, jadi total 2.00.

Minggu kedua: 2.00 + 0.50 = 2.50

Minggu ketiga: 2.50 + 0.50 = 3.00

Benar, 3 minggu.

Soalnya dalam dollar, dan semua angka desimal, tapi hitungannya sama saja dengan pecahan.

Saya juga bisa menggunakan pecahan. $1.50 / $0.50 = 3/1 = 3.

Jadi, jawabannya harusnya 3 minggu.

Tapi pastikan aku tidak salah. Soalnya: how many weeks does she need to save for the remaining amount.

Remaining amount adalah $1.50.

Per week save $0.50.

Banyaknya minggu = jumlah yang dibutuhkan ÷ jumlah per minggu.

Dalam hal ini, 1.50 / 0.50.

Jika menggunakan pecahan: 3/2 ÷ 1/2? Tunggu, lebih baik jangan confound dengan pecahan.

3.00 - 1.50 = 1.50, yes.

1.50 ÷ 0.50.


Extracted:
.
********************Question:
John starts at an elevation of 400 feet.  He travels downward at a rate of 10 feet down per minute for 5 minutes.  What is his elevation now?
Answer:
350
Response:
<think>
First, the problem says John starts at an elevation of 400 feet. He travels downward at a rate of 10 feet down per minute for 5 minutes. I need to find his elevation now.

Elevation is like height above sea level or ground level. Starting from 400 feet, which is high up. He's going down, so his elevation decreases.

The rate is 10 feet down per minute. So, it's decreasing by 10 feet every minute.

He does this for 5 minutes.

So, in 5 minutes, with 10 feet per minute, how much total descent?

Let me calculate that.

Change in elevation: 10 feet down per minute * 5 minutes.

Downward means we're subtracting, so elevation decreases.

So, total decrease: 10 ft/min * 5 min = 50 feet.

Now, original elevation was 400 feet.

So, current elevation: 400 - 50 = 350 feet.

Let me think if there's any trick here. The elevation given is 400 feet, and we're dealing with feet, so units are consistent.

Time is 5 minutes, rate is per minute, so no issues with time units.

Elevation change is simply distance divided by time, but here it's given as rate of descent, so directly.

I can think of it as a linear change.

Let t be time in minutes.

Elevation = initial elevation - rate * time

Rate is 10 feet down per minute, so -10 * t.

Then, at t=5, elevation = 400 - 10*5 = 400 - 50 = 350 feet.

Yes.

If the rate was positive, but it says "downward", so it's negative.

But in elevation terms, if up is positive, then down is negative.

Sometimes people might think of elevation as always positive, but 400 - 50 = 350, still positive, which makes sense.

No issues with negative elevation here.

So, I think 350 feet is the answer.

The problem says "for 5 minutes." I assume that's exactly 5 minutes, no fractions or anything.

Also, "travels downward at a rate of 10 feet down per minute" – it's clear.

Perhaps I should consider if the descent is constant rate, which it is, since it says "at a rate."

So, no acceleration or anything.

Therefore, it should be straightforward.

Now, the user said to think in Bahasa Indonesia, but I need to provide the working out.

I think I need to respond in English, since the problem is in English.

The user said "Think about the problem and provide your working out. You must think in Bahasa Indonesia."

"Think" in Bahasa Indonesia, but provide the working out in English?

Maybe the thinking process should be in Bahasa Indonesia, but the answer in English.

But the response should have the thinking and the final answer.

Perhaps I need to write the reasoning in Bahasa Indonesia first.

But since the user said "provide your working out," I think the working out can be in English, but thinking in Bahasa Indonesia.

Re-reading the user message: "You must think in Bahasa Indonesia."

And "provide your working out."

Probably, the thinking process should be in Bahasa Indonesia, but since it's a reasoning step, I can do it both ways.

But for consistency, perhaps I should write the reasoning in English first, as per the instruction to "think about the problem," and then provide the answer.

But the user specified "You must think in Bahasa Indonesia."

Let me read carefully.

User: "Think about the problem and provide your working out. You must think in Bahasa Indonesia."

So, all thinking should be in Bahasa Indonesia.

Then, the working out might include that.

Perhaps in the response, I should have the thought process in Bahasa Indonesia.

Since this is a simulation, I need to output in a way that shows reasoning.

I think for the purpose of this exercise, I can provide the answer directly, but with thinking steps.

Let me just state the answer first.

John starts at 400 feet elevation.

He descends at 10 feet per minute
Extracted:
,
********************Question:
Edmund is buying a new computer and needs to save up $75 before he has enough. He convinces his parents to pay him for extra chores. He normally has to do 12 chores a week. His parents agree to pay him $2 for every extra chore he does during the week. If he does 4 chores a day for two weeks, how much does he earn?
Answer:
64
Response:
<think>
Pertama-tama, Edmund membutuhkan $75 untuk membeli komputernya. Dia mendapatkan uang dengan mengerjakan tugas ekstrakurikuler tambahan untuk orang tuanya.

Dia biasanya harus mengerjakan 12 tugas per minggu. Orang tuanya akan membayar $2 untuk setiap tugas ekstra yang dia lakukan.

Dia berencana mengerjakan 4 tugas per hari selama dua minggu. Tapi, pertama-tama, saya harus memahami variabelnya.

Pertanyaannya: jika dia mengerjakan 4 tugas per hari selama dua minggu, berapa banyak uang yang dia dapatkan?

Tapi, dia hanya dibayar untuk tugas ekstra, bukan untuk tugas biasanya. Tugas biasanya dia kerjakan tanpa bayaran.

Soalnya: "His parents agree to pay him $2 for every extra chore he does during the week."

Jadi, dia hanya dibayar untuk tugas ekstra, yaitu tugas yang diluar jumlah biasa.

Jumlah tugas biasanya adalah 12 per minggu.

Jika dia mengerjakan 4 tugas per hari, itu harus dikonversi ke dalam jumlah total tugas selama dua minggu.

Ada 7 hari dalam satu minggu, bukan?

Jadi, untuk satu minggu:

Dia mengerjakan 4 tugas per hari. Tapi berapa hari? Problem mengatakan "for two weeks", jadi dua minggu.

Setiap minggu memiliki 7 hari, jadi total hari dalam dua minggu adalah 14 hari.

Jadi, dia mengerjakan 4 tugas/hari * 14 hari = 56 tugas.

Tapi, ini termasuk tugas biasanya dan ekstra?

Tidak, problem tidak menyebutkan bahwa dia mengerjakan tugas biasuasanya atau tidak.

Dalam konteksnya, dia melakukan 4 tugas per hari, tetapi tugas biasanya adalah bagian dari ini atau terpisah?

Mari kita baca problem lagi.

"Edmund is buying a new computer and needs to save up $75 before he has enough. He convinces his parents to pay him for extra chores. He normally has to do 12 chores a week. His parents agree to pay him $2 for every extra chore he does during the week. If he does 4 chores a day for two weeks, how much does he earn?"

Jadi, dia mengerjakan 4 tugas per hari selama dua minggu.

Tapi, normally 12 chores a week, yang berarti 12 tugas per minggu.

Jika dia mengerjakan 4 tugas per hari, maka untuk satu minggu, dia mengerjakan 4 tugas/hari * 7 hari = 28 tugas.

Dari 28 tugas itu, berapa yang merupakan tugas biasa dan berapa yang ekstra?

Tugas biasa adalah 12 per minggu, jadi ekstra adalah 28 - 12 = 16 tugas ekstra per minggu.

Itu untuk satu minggu.

Mereka membayar hanya untuk ekstra, jadi $2 per ekstra.

Jadi untuk satu minggu, dia mendapatkan 16 ekstra * $2 = $32.

Tapi ini untuk satu minggu.

Dia melakukan ini untuk dua minggu.

Jadi untuk dua minggu, total ekstra chores.

Pertama, perlu memastikan apakah hari-hari dalam dua minggu adalah hari yang dia kerjakan tugas biasanya atau tidak.

Normal chores: 12 per week, berarti hanya untuk 7 hari tertentu.

Tapi, dia melakukan 4 chores per day for two weeks.

Jadi, mungkin dia melakukan semua 12 tugas biasanya ditambah ekstra.

Saya harus menjelaskan dengan jelas.

Bilangan biasanya 12 chores per week, yang berarti dalam satu minggu, dia harus melakukan 12 tugas.

Jika dia melakukan 4 tugas per hari untuk setiap hari
Extracted:
,
********************Question:
Dennis collected 10 rocks. He put all of them in his aquarium but his fish ate half of them. He was able to make the fish spit two out. How many of Dennis's rocks are left?
Answer:
7
Response:
<think>
Saya perlu menyelesaikan masalah ini. Dennis mengumpulkan 10 batu. Dia menaruh semuanya di akuariumnya, tapi ikan-ikannya memakan separuh dari mereka. Kemudian, dia berhasil membuat ikan itu membuang dua batu. Pertanyaannya adalah, berapa banyak batu yang tersisa?

Pertama, mari kita pahami apa yang terjadi. Dennis memiliki 10 batu. Ikan memakan separuh dari mereka. Jadi, setengah dari 10 adalah 5. Jadi, ikan memakan 5 batu.

Sekarang, setelah itu, Dennis membuat ikan itu membuang dua batu. Ini mungkin berarti ikan itu memberikan dua batu itu ke Dennis atau sesuatu yang semacamnya. Tapi, dalam konteks ini, "spit" bisa berarti membuang atau mengeluarkannya.

Jadi, setelah ikan memakan 5 batu, batu yang tersisa adalah 10 - 5 = 5.

Lalu, Dennis membuat ikan itu membuang dua batu. Batu yang dibuang ini adalah bagian dari batu yang sudah dimakan atau yang tersisa?

Ini agak ambigu. Mari kita baca kembali pernyataannya: "He made the fish spit two out." "Spit out" bisa berarti ikan mengeluarkan dua batu itu yang sudah dimakannya atau dari batu yang tersisa.

Dalam konteks ini, setelah ikan memakan separuh, ada 5 batu yang dimakan dan 5 yang tersisa. Tapi kemudian, dia membuat ikan itu membuang dua batu. Batu apa yang dibuang?

Kemungkinan ada dua interpretasi:

1. Ikan membuang dua batu yang sudah dimakannya. Tapi, jika ikan sudah memakannya, bagaimana ikan bisa membuangnya kembali? Ini tidak logis.

2. Ikan membuang dua batu yang masih tersisa. Jadi, dari 5 batu yang tersisa, ikan membuang dua.

Atau, mungkin "spit out" merujuk pada batu yang dimakannya, tapi ini rumit.

Mari kita pikirkan secara berurutan. Setelah ikan memakan separuh, 5 batu hilang, 5 tersisa.

Kemudian, Dennis membuat ikan itu membuang dua batu. Mungkin, ikan ini membuang dua batu dari batu yang dimakannya karena sesuatu, atau dari yang tersisa.

Tapi, ini tidak jelas. Mari kita perhatikan bahwa masalahnya mungkin berusaha menyembunyikan informasi yang ambigu.

Kata-kata: "He put all of them in his aquarium but his fish ate half of them." Jadi, dia memasukkan semua 10, lalu ikan memakan setengah, jadi 5 dimakan, 5 tersisa.

" He was able to make the fish spit two out." "Spit out" bisa berarti mengeluarkan atau membuang.

Dalam bahasa Inggris, "spit out" sering kali berarti mengeluarkan sesuatu dari mulut, seperti memuntahkannya. Jadi, mungkin merujuk pada batu yang sudah dimakan.

Tapi, jika ikan sudah memakannya, bagaimana bisa mengeluarkannya? Itu tidak masuk akal.

Mungkin ini adalah metafora atau sesuatu yang anunceng. Dalam konteks teka-teki, kadang-kadang ada trik bahasa.

Kata "spit out" bisa juga berarti dia mengeluarkan dua batu dengan cara yang sama, tapi tidak terkait dengan yang dimakan.

Mari kita asumsikan bahwa setelah ikan memakan 5 batu, ada 5 batu yang tersisa. Lalu, Dennis membuat ikan itu membuang dua dari batu yang tersisa.

Jadi, 5 - 2 = 3 batu yang tersisa.

Tapi masalahnya adalah
Extracted:
.
********************Question:
A department store offers a 10% discount for the amount exceeding $100 of the customer's total charge. Jaco bought a pair of shoes for $74; 2 pairs of socks that cost $2 per pair; a bag that costs $42. How much will Jaco pay for those items?
Answer:
118
Response:
<think>
Baik, mari kita selesaikan masalah matematika ini. Soalnya adalah department store memberikan diskon 10% untuk jumlah total yang melebihi $100. Jaco membeli sepasang sepatu seharga $74, dua pasang kaos kaki yang masing-masing $2, dan satu tas seharga $42. Kita perlu menghitung berapa banyak yang harus dibayar oleh Jaco.

Langkah pertama, mari menghitung total harga semua item tanpa diskon. Ada sepatu $74, dua pasang kaos kaki masing-masing $2, dan tas $42.

Dua pasang kaos kaki dihitung 2 * $2 = $4.

Jadi, total tanpa diskon = $74 (sepatu) + $4 (kaos kaki) + $42 (tas) =.....

74 + 4 = 78, kemudian 78 + 42 = 120. Nunggu ta, mari hitung lagi: 74 + 4 = 78, dan 78 + 42.

78 + 40 = 118, lalu 118 + 2 = 120. Benar, totalnya $120.

Sekarang, aturannya: diskon 10% untuk jumlah yang melebihi $100. Jadi, karena totalnya $120 yang lebih besar dari $100, maka kita berikan diskon 10% pada bagian yang melebihi $100.

Melebihi $100 berapa? $120 - $100 = $20. Jadi, hanya $20 yang mendapatkan diskon 10%.

Diskon 10% dari $20 = 10/100 * 20 = 2/10 * 20 = 2 * 2 = 4. Jadi, diskon $4.

Maka, total yang harus dibayar adalah total tanpa diskon minus diskon = $120 - $4 = $116.

Atau bisa juga dengan cara lain. Total tanpa diskon $120, batas $100 tidak mendapatkan diskon? Sepertinya tidak, karena yang diskon adalah jumlah yang melebihi.

Perhatikan lagi: "10% discount for the amount exceeding $100". Jadi, hanya bagian yang melebihi $100 yang dikenakan diskon.

Jadi, kita tidak diskon $100 pertama, hanya diskon bagian yang lebih.

Total $120, excess $20, diskon 10% dari excess, yaitu $2, jadi bayar (100 + 20 - 2) = 100 + 18 = 118? Tunggu.

100 + excess - diskon dari excess.

Excess $20, diskon 10% dari $20 adalah $2, jadi bayar untuk excess sebesar $18.

Sebelum excess seharga $100, di mana tidak ada diskon.

Jadi, total bayar = $100 + $18 = $118.

Kira-kira berbeda dengan yang saya hitung tadi. Mungkin ada kesalahan.

Pertama, total tanpa diskon $120.

Jika yang melebihi adalah $20, lalu diskon 10% untuk excess.

Jadi, harga efektif untuk excess adalah $20 - 0.10*$20 = $18.

Kemudian, untuk bagian yang tidak melebihi (maks. $100), bayar penuh.

Tapi di sini, excess adalah $20, jadi bayar $18 untuk excess dan $100 untuk bagian bawah.

Tapi bagian bawah itu hanya sampai $100 dari total.

Mari
Extracted:
,
********************Question:
Samir just turned half the age Hania was 10 years ago. If in five years Hania will be 45 years old, what will Samir's age be five years from now?
Answer:
20
Response:
<think>
Pertama-tama, aku perlu memahami masalahnya. Samir sekarang adalah setengah dari umurnya Hania 10 tahun yang lalu. Juga, dalam lima tahun, Hania akan berusia 45 tahun. Aku perlu mencari umur Samir dalam lima tahun.


Unrecognized keys in `rope_scaling` for 'rope_type'='yarn': {'attn_factor'}

TrainOutput(global_step=100, training_loss=0.02300157090324224, metrics={'train_runtime': 14240.0277, 'train_samples_per_second': 0.028, 'train_steps_per_second': 0.007, 'total_flos': 0.0, 'train_loss': 0.02300157090324224})

<a name="Inference"></a>
### Inference
Now let's try the model we just trained! First, let's first try the model without any GRPO trained:

In [27]:
text = "What is the sqrt of 101?"

from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 1024,
)
output = model.fast_generate(
    [text],
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

" - We the Geeks\nWe the Geeks\nAsk a question\nGet an answer to your question\nPost an article\nGet new and useful information\nLog in\nWhat is the sqrt of 101?\nI have a number, 101, and I need to find the square root. I know that 10^2 = 100, and 11^2 = 121, so the square root of 101 is between 10 and 11. I am using a calculator, and I get 10.049875, but I need to know the exact value. I need the exact value, not a decimal. I need the exact value, but 10.049875 is a decimal, that's not exact. I need the exact value, but 10.049875 is a decimal, I need the exact value, but 10.049870, I should use a different method. I can use the long division method to find the square root. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long division method. I can use the long"

And now with the LoRA we just trained with GRPO - we first save the LoRA first!

In [28]:
model.save_lora("grpo_lora")

Unrecognized keys in `rope_scaling` for 'rope_type'='yarn': {'attn_factor'}

Verify LoRA is actually trained!

In [29]:
from safetensors import safe_open

tensors = {}
with safe_open("grpo_lora/adapter_model.safetensors", framework = "pt") as f:
    # Verify both A and B are non zero
    for key in f.keys():
        tensor = f.get_tensor(key)
        n_zeros = (tensor == 0).sum() / tensor.numel()
        assert(n_zeros.item() != tensor.numel())

Now we load the LoRA and test. We tested without using our custom system prompt which should not (or minimal) affect toward the model's original reasoning ability.:

In [30]:
messages = [
    {"role": "user",   "content": "Solve (x + 2)^2 = 0"},
]

text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
    tokenize = False,
)
from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 2048,
)
output = model.fast_generate(
    text,
    sampling_params = sampling_params,
    lora_request = model.load_lora("grpo_lora"),
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

'<think>\nI have the equation (x + 2)² = 0. I need to solve for x. This is a simple equation, but I should be careful.\n\nFirst, I know that (x + 2)² is a perfect square, and it\'s set equal to zero. The only number that, when squared, gives zero is zero itself. So, (x + 2) must be equal to zero.\n\nIf (x + 2) is not zero, then (x + 2)² would be positive, not zero. For example, if x + 2 is 1, then 1² = 1, not 0. If it\'s -1, (-1)² = 1, again not 0. So, (x + 2) has to be 0 for the square to be 0.\n\nSo, (x + 2) = 0.\n\nNow, to find x, I can solve for x. x + 2 = 0, so x = -2.\n\nI can also think of this in terms of the zero product property. The zero product property says that if a * b = 0, then a = 0 or b = 0. In this case, (x + 2) * (x + 2) = 0, so (x + 2) = 0.\n\nThere are no other factors, so that\'s the only solution.\n\nI can take the square root of both sides. The square root of (x + 2)² is |x + 2|, and the square root of 0 is 0, so |x + 2| = 0, which again means x + 2 = 0, so x = -2.\n\nThe absolute value is 0, so it\'s just 0, not -0.\n\nI can also think of the graph. (x + 2)² is a parabola that opens upwards, and it touches the x-axis at x = -2, and that\'s the only point, so the root is at x = -2.\n\nThe equation (x + 2)² = 0 is a bit different from, say, (x + 2)² = 4, which has two solutions, but when it\'s set to zero, it\'s a double root or something, but in this case, it\'s just one solution.\n\nI can use the quadratic formula, but this is not a standard quadratic. (x + 2)² = 0 is the same as x² + 4x + 4 = 0, if I expand it.\n\nx² + 4x + 4 = 0.\n\nNow, I can use the quadratic formula. a = 1, b = 4, c = 4.\n\nDiscriminant = b² - 4ac = 16 - 16 = 0, so one real root, x = -b/2a = -4/2 = -2.\n\nSame thing.\n\nI can factor: (x + 2)(x + 2) = 0, so x = -2 is the only solution.\n\nI think I\'m overcomplicating this. The answer should be x = -2.\n\nThe problem is to solve, and I need to present the answer.\n\nI should write it in a box, as per the instruction.\n\nBut is there any other way to think about this? For example, in complex numbers, but this is a real equation, and for real x, it\'s -2.\n\n(x + 2)² = 0, and in real numbers, x = -2 is the only solution.\n\nI can think of it as a function, f(x) = (x + 2)², and f(x) = 0, so set to zero.\n\nThe domain is all real numbers, and the range is [0, ∞), and it hits zero at x = -2.\n\nI think I\'m good.\n\nSo, the solution is x = -2.\n\nThe problem says "Solve (x + 2)^2 = 0", and I need to say the value of x.\n\nOr as a set, {x | (x + 2)^2 = 0} = {-2}.\n\nBut I think for the context, x = -2 is fine.\n\nNow, to present the answer.\n\nI should write: The solution is x = -2.\n\nAnd then put it in a box.\n\nThe instruction is to put the final answer in a box, so just the value, I think.\n\nNo, for solving, it\'s x = -2.\n\nSince it\'s an equation, the solution is x = -2.\n\nI can write the answer as x = -2.\n\nI think that\'s it.\n\nI should check if the problem is for a specific'

Next, let's test using our system prompt which should use the new language :

In [31]:
messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user",   "content": "Solve (x + 2)^2 = 0"},
]

text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
    tokenize = False,
)
from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 2048,
)
output = model.fast_generate(
    text,
    sampling_params = sampling_params,
    lora_request = model.load_lora("grpo_lora"),
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

'<think>\nPertama, soalnya adalah: "Solve (x + 2)^2 = 0". Saya perlu menyelesaikan persamaan ini. Karena user meminta untuk berpikir dalam Bahasa Indonesia, saya akan bekerja dengan konsep aljabar sederhana.\n\nPersamaan ini adalah (x + 2)² = 0. Saya tahu bahwa suatu bilangan kuadrat selalu non-negatif, jadi (x + 2)² = 0 berarti (x + 2)² itu nol. Dalam aljabar, ketika suatu binomial dikuadratkan dan hasilnya nol, itu berarti binomial itu sendiri harus nol. Jadi, (x + 2) = 0.\n\nDari sini, x = -2. Tapi biar saya verifikasi. Saya bisa memfaktorkan persamaan ini. (x + 2)² = 0, jadi solusinya adalah x = -2, dan ini adalah solusi ganda (repeated root) karena persamaan ini menyinggung sumbu x di x = -2.\n\nJadi, solusinya adalah x = -2. Saya perlu menuliskan jawabannya dengan jelas. Mungkin user ingin tahu langkah-langkahnya, jadi saya akan menuliskan penalaran logis.\n\nDalam konteks soal, mungkin ini untuk memperjelas konsep penyelesaian persamaan kuadrat. Tapi di sini, persamaan ini sederhana, jadi jawabannya sebenarnya cuma satu solusi.\n\nSaya perlu memastikan tidak ada kesalahan. Saya bisa memeriksa dengan substitusi. Jika x = -2, maka ( -2 + 2 )² = 0² = 0, benar, memenuhi persamaan. Tidak ada solusi lain, karena kuadrat selalu positif kecuali nol.\n\nJadi, solusi tunggalnya adalah x = -2. Saya akan menuliskan jawabannya.\n</think>\nSoal: Selesaikan persamaan (x + 2)² = 0.\n\nPertama, perhatikan bahwa (x + 2)² = 0 menandakan bahwa kuadrat dari (x + 2) adalah nol. Dalam aljabar, suatu bilangan yang dikuadratkan dan hasilnya nol berarti bilangan itu sendiri adalah nol. Jadi, (x + 2) = 0.\n\nDari sini, kita selesaikan untuk x:  \nx + 2 = 0  \nx = -2\n\nJadi, solusi untuk persamaan (x + 2)² = 0 adalah x = -2.  \nNote: Solusi ini adalah solusi ganda (repeated root) karena persamaan ini menyinggung sumbu x di x = -2.'

Lets compare our results with system prompt but without our LoRA

In [32]:
messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user",   "content": "Solve (x + 2)^2 = 0"},
]

text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
    tokenize = False,
)
from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 2048,
)
output = model.fast_generate(
    text,
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

'<think>\nPertama, soalnya adalah: "Solve (x + 2)^2 = 0". Saya perlu menyelesaikan persamaan ini. Karena user meminta untuk berpikir dalam Bahasa Indonesia, saya akan bekerja dengan hati-hati.\n\nPersamaan ini adalah (x + 2)² = 0. Saya tahu bahwa suatu kuadrat sama dengan nol hanya ketika bagian di dalamnya adalah nol. Jadi, (x + 2)² = 0 berarti (x + 2) = 0, karena tidak mungkin suatu bilangan negatif kuadrat menghasilkan nol, kecuali nilainya nol.\n\nJadi, (x + 2) = 0. Maka, x = -2.\n\nSekarang, apakah ini solusinya? Saya perlu memeriksa. Jika x = -2, maka (x + 2) = 0, dan 0² = 0, jadi memang benar. Tidak ada solusi lain, karena persamaan ini adalah persamaan kuadrat, tetapi reduksi sederhananya menunjukkan satu-satunya solusi.\n\nDalam konteks metrik, solusi x = -2 adalah solusi ganda, artinya akar dengan multiplicitas 2, tetapi solusinya tetap x = -2.\n\nJadi, solusinya adalah x = -2.\n\nSekarang, bagaimana cara menuliskannya? Saya perlu menyesuaikan jawaban dengan memikirkan dalam Bahasa Indonesia, meskipun user meminta solusi, mungkin penjelasan pun.\n\nPertama, identifikasi step by step.\n\nStep 1: (x + 2)² = 0\n\nStep 2: Ambil akar kuadrat dari kedua sisi, ingat akar kuadrat nol adalah nol, jadi (x + 2) = 0\n\nStep 3: Sehingga, x = -2\n\nDalam matematika, aturan umum untuk memecahkan persamaan kuadrat, meski murni, jadi:\n\nJika a(x - b)² = 0, maka x = b.\n\nAtau, umumnya, (x - a)² = 0, x = a.\n\nPada contoh, (x + 2)² = 0, jadi a = -2, jadi x = -2.\n\nJadi, solusinya adalah x = -2.\n\nSekarang, apakah user meminta solusi dalam format tertentu? Tidak, cuma "Solve (x + 2)^2 = 0", jadi mungkin solusi x = -2.\n\nSaya perlu memastikan ekspresi diterima. (x + 2)² = 0, setara dengan x² + 4x + 4 = 0, lalu selesaikan.\n\nDengan memfaktorkan, (x + 2)(x + 2) = 0, jadi x = -2 (dengan multiplicitas 2, tetapi solusinya tetap -2).\n\nDalam diskriminan, D = 0, jadi x = -b/2a, jadi a=1, b=4, c=4, D=16-16=0, jadi x = -4/2*1 = -2.\n\nJadi, konsisten.\n\nJawabannya: x = -2\n\nSekarang, bagaimana menuliskannya? Saya perlu menyalin dan memerintahkan output.\n\nKarena user meminta "provide your working out" dan "must think in Bahasa Indonesia", mungkin output punya jawapan.\n\nJadi, saya perlu menulis respons dengan step by step di dalam Bahasa Indonesia.\n\nKatakanlah: "Untuk menyelesaikan persamaan (x + 2)² = 0, kita set (x + 2) = 0, karena suatu bilangan kuadrat nol hanya ketika bilangan itu nol. Maka, x = -2"\n\nTapi, mungkin perlu penjelasan yang komprehensif.\n\nJadi, rencananya: \n- Pernyataan awal: Diketahui persamaan (x + 2)² = 0\n- Kita'

Let's take 20 samples, and compare the the amount of using our LoRA and not using it, and see which one has better amount of correct language

In [33]:
sample_dataset = dataset.shuffle(seed = 3407).select(range(20))
sample_dataset

Dataset({
    features: ['prompt', 'solution', 'answer'],
    num_rows: 20
})

In [34]:
with_lora_id_count = 0
without_lora_id_count = 0

print("Comparing language usage with and without LoRA on 20 samples:")
print("=" * 60)

for i, sample in enumerate(sample_dataset):
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": sample["prompt"][1]["content"]},
    ]

    text = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt = True,
        tokenize = False,
    )

    output_with_lora = model.fast_generate(
        text,
        sampling_params = sampling_params,
        lora_request = model.load_lora("grpo_lora"),
    )[0].outputs[0].text

    output_without_lora = model.fast_generate(
        text,
        sampling_params = sampling_params,
        lora_request = None,
    )[0].outputs[0].text

    lang_with_lora = get_lang(output_with_lora)
    lang_without_lora = get_lang(output_without_lora)

    if lang_with_lora == 'id':
        with_lora_id_count += 1
    if lang_without_lora == 'id':
        without_lora_id_count += 1

    # Print progress every 5 samples
    if (i + 1) % 5 == 0:
        print(f"Processed {i + 1}/20 samples...")

print("\n" + "=" * 60)
print("RESULTS:")
print(f"With LoRA - Indonesian responses: {with_lora_id_count}/20 ({with_lora_id_count/20*100:.1f}%)")
print(f"Without LoRA - Indonesian responses: {without_lora_id_count}/20 ({without_lora_id_count/20*100:.1f}%)")
print(f"Improvement: +{with_lora_id_count - without_lora_id_count} Indonesian responses with LoRA")

Comparing language usage with and without LoRA on 20 samples:
============================================================

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed 5/20 samples...

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed 10/20 samples...

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed 15/20 samples...

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed 20/20 samples...

============================================================
RESULTS:
With LoRA - Indonesian responses: 20/20 (100.0%)
Without LoRA - Indonesian responses: 20/20 (100.0%)
Improvement: +0 Indonesian responses with LoRA

Our reasoning model is much better - it's not always correct, since we only trained it for an hour or so - it'll be better if we extend the sequence length and train for longer!

<a name="Save"></a>
### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens. See [our docs](https://unsloth.ai/docs/basics/inference-and-deployment) for more deployment options.

In [37]:
# Merge to 16bit
if False: model.save_pretrained_merged("deepseek_r1_finetune_16bit", tokenizer, save_method = "merged_16bit",)
if True: model.push_to_hub_merged("arefehRajabian/deepseek_r1_finetune_16bit", tokenizer, save_method = "merged_16bit", token = "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")

# Merge to 4bit
if False: model.save_pretrained_merged("deepseek_r1_finetune_4bit", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("HF_USERNAME/deepseek_r1_finetune_4bit", tokenizer, save_method = "merged_4bit", token = "YOUR_HF_TOKEN")

# Just LoRA adapters
if False:
    model.save_pretrained("deepseek_r1_lora")
    tokenizer.save_pretrained("deepseek_r1_lora")
if False:
    model.push_to_hub("HF_USERNAME/deepseek_r1_lora", token = "YOUR_HF_TOKEN")
    tokenizer.push_to_hub("HF_USERNAME/deepseek_r1_lora", token = "YOUR_HF_TOKEN")

config.json:   0%|          | 0.00/911 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Unrecognized keys in `rope_scaling` for 'rope_type'='yarn': {'attn_factor'}

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...tune_16bit/tokenizer.json:  68%|######8   | 7.78MB / 11.4MB

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub
Checking cache directory for required files...
Cache check failed: model-00001-of-00004.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.90G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files:  25%|██▌       | 1/4 [03:12<09:36, 192.26s/it]

model-00002-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files:  50%|█████     | 2/4 [06:43<06:46, 203.25s/it]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files:  75%|███████▌  | 3/4 [10:07<03:23, 203.80s/it]

model-00004-of-00004.safetensors:   0%|          | 0.00/1.58G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files: 100%|██████████| 4/4 [11:17<00:00, 169.46s/it]

Note: tokenizer.model not found (this is OK for non-SentencePiece models)

Unsloth: Merging weights into 16bit:   0%|          | 0/4 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...0001-of-00004.safetensors:   0%|          | 16.0MB / 4.90GB

Unsloth: Merging weights into 16bit:  25%|██▌       | 1/4 [04:11<12:35, 251.76s/it]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...0002-of-00004.safetensors:   0%|          |  601kB / 4.92GB

Unsloth: Merging weights into 16bit:  50%|█████     | 2/4 [08:26<08:26, 253.28s/it]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...0003-of-00004.safetensors:   0%|          |  601kB / 4.98GB

Unsloth: Merging weights into 16bit:  75%|███████▌  | 3/4 [13:12<04:28, 268.46s/it]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...0004-of-00004.safetensors:   2%|2         | 31.9MB / 1.58GB

Unsloth: Merging weights into 16bit: 100%|██████████| 4/4 [14:20<00:00, 215.20s/it]

Unsloth: Merge process complete. Saved to `/content/arefehRajabian/deepseek_r1_finetune_16bit`

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [docs page](https://unsloth.ai/docs/basics/inference-and-deployment/saving-to-gguf)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

[**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)

In [36]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("deepseek_r1_finetune", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False: model.push_to_hub_gguf("HF_USERNAME/deepseek_r1_finetune", tokenizer, token = "YOUR_HF_TOKEN")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("deepseek_r1_finetune", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("HF_USERNAME/deepseek_r1_finetune", tokenizer, quantization_method = "f16", token = "YOUR_HF_TOKEN")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("deepseek_r1_finetune", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("HF_USERNAME/deepseek_r1_finetune", tokenizer, quantization_method = "q4_k_m", token = "YOUR_HF_TOKEN")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "HF_USERNAME/deepseek_r1_finetune", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "YOUR_HF_TOKEN",
    )

Now, use the `deepseek_r1_finetune.Q8_0.gguf` file or `deepseek_r1_finetune.Q4_K_M.gguf` file in llama.cpp.

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other resources:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
4. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://unsloth.ai/docs/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>

  This notebook and all Unsloth notebooks are licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).