To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your local device, follow [our guide](https://unsloth.ai/docs/get-started/install). This notebook is licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & how to save it

### News

Introducing **[Unsloth Desktop](https://unsloth.ai/docs/desktop)**, the first desktop app to run and train models. Free and open-source for macOS, Windows and Linux. [GitHub](https://github.com/unslothai/unsloth) • [Download](https://unsloth.ai/download)

<p>
<a href="https://unsloth.ai/docs/desktop"><img src="https://raw.githubusercontent.com/unslothai/notebooks/refs/heads/main/assets/unsloth-qwen3-8.png" width="350" alt="Introducing Unsloth Desktop"></a>
</p>

Train MoEs - DeepSeek, GLM, Qwen and gpt-oss 12x faster with 35% less VRAM. [Blog](https://unsloth.ai/docs/new/faster-moe)

Ultra Long-Context Reinforcement Learning is here with 7x more context windows! [Blog](https://unsloth.ai/docs/new/grpo-long-context)

New in Reinforcement Learning: [FP8 RL](https://unsloth.ai/docs/new/fp8-reinforcement-learning) • [Vision RL](https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl) • [Standby](https://unsloth.ai/docs/basics/memory-efficient-rl) • [gpt-oss RL](https://unsloth.ai/docs/new/gpt-oss-reinforcement-learning)

Visit our docs for all our [model uploads](https://unsloth.ai/docs/get-started/unsloth-model-catalog) and [notebooks](https://unsloth.ai/docs/get-started/unsloth-notebooks).

### Installation

In [1]:
%%capture
import os
os.environ["UNSLOTH_VLLM_STANDBY"] = "1" # [NEW] Extra 30% context lengths!
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install or uv pip install
    !pip install unsloth vllm
else:
    pass # For Colab / Kaggle, we need extra instructions hidden below \/

In [2]:
#@title Colab Extra Install { display-mode: "form" }
%%capture
import os
!pip install --upgrade -qqq uv
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install!
    !pip install unsloth vllm
else:
    try: import numpy, PIL; _numpy = f'numpy=={numpy.__version__}'; _pil = f'pillow=={PIL.__version__}'
    except: _numpy = "numpy"; _pil = "pillow"
    try: import subprocess; is_t4 = "Tesla T4" in str(subprocess.check_output(["nvidia-smi"]))
    except: is_t4 = False
    _vllm, _triton = ('vllm==0.11.2', 'triton') if is_t4 else ('vllm==0.15.1', 'triton')
    !uv pip install -qqq --upgrade {_vllm} {_numpy} {_pil} torchvision bitsandbytes xformers unsloth
    !uv pip install -qqq {_triton}
    try:
        import importlib.metadata as _md; _torch_v = tuple(int(_p) for _p in _md.version("torch").split("+")[0].split(".")[:2])
    except Exception:
        _torch_v = ()
    # torchao 0.18.0 imports torch.nn.functional.ScalingType, added in torch 2.10; peft >= 0.19 needs the 0.16.0 floor.
    _torchao = "torchao>=0.16.0" if _torch_v >= (2, 10) else "torchao>=0.16.0,<0.18.0"
    !uv pip install -qqq --no-deps --upgrade "{_torchao}"
!uv pip install transformers==4.56.2
!uv pip install --no-deps trl==0.22.2

### Unsloth

Load up `Phi-4 14B`, and set parameters

In [3]:
from unsloth import FastLanguageModel, is_bfloat16_supported
import torch
max_seq_length = 512 # Can increase for longer reasoning traces
lora_rank = 16 # Larger rank = smarter, but slower

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Phi-4-mini-reasoning",
    max_seq_length = max_seq_length,
    load_in_4bit = True, # False for LoRA 16bit
    fast_inference = True, # Enable vllm fast inference
    max_lora_rank = lora_rank,
    gpu_memory_utilization = 0.9, # Reduce if out of memory
)

model = FastLanguageModel.get_peft_model(
    model,
    r = lora_rank, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["gate_proj", "up_proj", "down_proj",],
    lora_alpha = lora_rank,
    use_gradient_checkpointing = "unsloth", # Enable long context finetuning
    random_state = 3407,
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/usr/local/lib/python3.13/dist-packages/unsloth/_gpu_init.py:243: UserWarning: torchcodec 0.11.0+cu128 is incompatible with torch 2.9.0+cu128; install a matching build with `pip install 'torchcodec>=0.9,<0.10.0'`.
  disable_torchcodec_if_broken()

ERROR 09-04 11:41:29 [fa_utils.py:64] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.9.2: Fast Phi3 patching. Transformers: 4.56.2. vLLM: 0.11.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Not planning a device map; vLLM places its own weights. Using `sequential`.
INFO 09-04 11:41:52 [vllm_utils.py:752] Unsloth: Patching vLLM v1 graph capture
Unsloth: Standby mode is enabled. However your setting of `gpu_memory_utilization` will OOM.
Changing `gpu_memory_utilization` to 0.76.
Unsloth: vLLM loading unsloth/phi-4-mini-reasoning-unsloth-bnb-4bit with actual GPU utilization = 75.26%
Unsloth: Your GPU has CUDA compute capability 7.5 with VRAM = 14.56 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 512. Num Sequences = 32.
Unsloth: vLLM's KV Cache can use up to 7.74 GB. Also swap space = 0 GB.
Unsloth: Not an error, but `use_cudagraph` is not supported in vLLM.config.CompilationConfig. Skipping.
WARNING 09-04 11:42:24 [compilation.py:610] Level is deprecated and will be removed in the next release,either 0.12.0 or 0.11.2 whichever is soonest.Use mode instead.If both level and mode are given,only mode will be used.
WARNING 09-04 11:42:24 [compilation.py:699] The 'use_inductor' flag is deprecated and will be removed in the next release (v0.12.0). Please use the 'backend' option instead.
Unsloth: Not an error, but `device` is not supported in vLLM. Skipping.
INFO 09-04 11:42:24 [utils.py:253] non-default args: {'load_format': 'bitsandbytes', 'dtype': torch.float16, 'seed': 0, 'max_model_len': 512, 'enable_prefix_caching': True, 'swap_space': 0, 'gpu_memory_utilization': 0.7526166896476574, 'max_num_batched_tokens': 4096, 'max_num_seqs': 32, 'max_logprobs': 0, 'disable_log_stats': True, 'quantization': 'bitsandbytes', 'enable_lora': True, 'enable_chunked_prefill': True, 'compilation_config': {'level': 3, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': [], 'splitting_ops': None, 'compile_mm_encoder': False, 'use_inductor': True, 'compile_sizes': None, 'inductor_compile_config': {'epilogue_fusion': True, 'max_autotune': False, 'shape_padding': True, 'trace.enabled': False, 'triton.cudagraphs': False, 'debug': False, 'dce': True, 'memory_planning': True, 'coordinate_descent_tuning': False, 'trace.graph_diagram': False, 'compile_threads': 4, 'group_fusion': True, 'disable_progress': False, 'verbose_progress': True, 'triton.multi_kernel': 0, 'triton.use_block_ptr': True, 'triton.enable_persistent_tma_matmul': True, 'triton.autotune_at_compile_time': False, 'triton.cooperative_reductions': False, 'cuda.compile_opt_level': '-O2', 'cuda.enable_cuda_lto': True, 'combo_kernels': False, 'benchmark_combo_kernel': True, 'combo_kernel_foreach_dynamic_shapes': True, 'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_cudagraph_capture_size': None, 'local_cache_dir': None}, 'enable_sleep_mode': True, 'model': 'unsloth/phi-4-mini-reasoning-unsloth-bnb-4bit'}

/usr/local/lib/python3.13/dist-packages/pydantic/type_adapter.py:607: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `enum` - serialized value may not be as expected [field_name='mode', input_value=3, input_type=int])
  return self.serializer.to_python(

INFO 09-04 11:42:25 [config.py:417] Replacing legacy 'type' key with 'rope_type'
INFO 09-04 11:42:37 [model.py:631] Resolved architecture: Phi3ForCausalLM
WARNING 09-04 11:42:37 [model.py:1971] Casting torch.bfloat16 to torch.float16.
INFO 09-04 11:42:37 [model.py:1745] Using max model len 512
INFO 09-04 11:42:38 [scheduler.py:216] Chunked prefill is enabled with max_num_batched_tokens=4096.
Unsloth: vLLM Bitsandbytes config using kwargs = {'load_in_8bit': False, 'load_in_4bit': True, 'bnb_4bit_compute_dtype': 'float16', 'bnb_4bit_quant_storage': 'uint8', 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': True, 'llm_int8_enable_fp32_cpu_offload': False, 'llm_int8_has_fp16_weight': False, 'llm_int8_skip_modules': ['lm_head', 'multi_modal_projector', 'merger', 'modality_projection', 'model.layers.3.mlp'], 'llm_int8_threshold': 6.0}

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/15.5M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/249 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/468 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/568 [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/198 [00:00<?, ?B/s]

INFO 09-04 11:42:43 [core.py:93] Initializing a V1 LLM engine (v0.11.2) with config: model='unsloth/phi-4-mini-reasoning-unsloth-bnb-4bit', speculative_config=None, tokenizer='unsloth/phi-4-mini-reasoning-unsloth-bnb-4bit', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=512, download_dir=None, load_format=bitsandbytes, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/phi-4-mini-reasoning-unsloth-bnb-4bit, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': 3, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer'], 'compile_mm_encoder': False, 'use_inductor': True, 'compile_sizes': [], 'inductor_compile_config': {'epilogue_fusion': True, 'max_autotune': False, 'shape_padding': True, 'trace.enabled': False, 'triton.cudagraphs': False, 'debug': False, 'dce': True, 'memory_planning': True, 'coordinate_descent_tuning': False, 'trace.graph_diagram': False, 'compile_threads': 4, 'group_fusion': True, 'disable_progress': False, 'verbose_progress': True, 'triton.multi_kernel': 0, 'triton.use_block_ptr': True, 'triton.enable_persistent_tma_matmul': True, 'triton.autotune_at_compile_time': False, 'triton.cooperative_reductions': False, 'cuda.compile_opt_level': '-O2', 'cuda.enable_cuda_lto': True, 'combo_kernels': False, 'benchmark_combo_kernel': True, 'combo_kernel_foreach_dynamic_shapes': True, 'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_cudagraph_capture_size': 64, 'local_cache_dir': None}
INFO 09-04 11:42:43 [parallel_state.py:1208] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:43749 backend=nccl
INFO 09-04 11:42:43 [parallel_state.py:1394] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0

/usr/local/lib/python3.13/dist-packages/pydantic/type_adapter.py:607: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `enum` - serialized value may not be as expected [field_name='mode', input_value=3, input_type=int])
  return self.serializer.to_python(

INFO 09-04 11:42:44 [topk_topp_sampler.py:36] Using FlashInfer for top-p & top-k sampling.
INFO 09-04 11:42:44 [gpu_model_runner.py:3259] Starting to load model unsloth/phi-4-mini-reasoning-unsloth-bnb-4bit...
INFO 09-04 11:42:45 [cuda.py:377] Using AttentionBackendEnum.FLASHINFER backend.
INFO 09-04 11:42:46 [bitsandbytes_loader.py:791] Loading weights with BitsAndBytes quantization. May take a while ...

model.safetensors:   0%|          | 0.00/3.00G [00:00<?, ?B/s]

INFO 09-04 11:43:10 [weight_utils.py:441] Time spent downloading weights for unsloth/phi-4-mini-reasoning-unsloth-bnb-4bit: 24.292567 seconds
INFO 09-04 11:43:11 [weight_utils.py:481] No model.safetensors.index.json found in remote.

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

INFO 09-04 11:43:15 [punica_selector.py:20] Using PunicaWrapperGPU.
INFO 09-04 11:43:16 [gpu_model_runner.py:3338] Model loading took 2.8900 GiB memory and 29.377036 seconds
INFO 09-04 11:43:30 [backends.py:631] Using cache directory: /root/.cache/vllm/torch_compile_cache/66568403ac/rank_0_0/backbone for vLLM's torch.compile
INFO 09-04 11:43:30 [backends.py:647] Dynamo bytecode transform time: 13.53 s

Unsloth: Compiling kernels: 100%|██████████| 1/1 [00:00<00:00,  1.13it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]

INFO 09-04 11:43:40 [backends.py:251] Cache the graph for dynamic shape for later use

Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 25.93it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 236.72it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 227.97it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 180.36it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 181.26it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 211.33it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 213.46it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 279.03it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 291.85it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 247.73it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 188.57it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 284.33it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 282.44it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 219.07it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 235.71it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 243.33it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 275.06it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 209.67it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 269.45it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 260.80it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 235.47it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 221.57it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 218.85it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 245.65it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 230.84it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 280.29it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 242.71it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 219.64it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 241.92it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 261.82it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 261.84it/s, triton_poi_fused_add_cat_index_select_mul_neg_repeat_slice_split_split_with_sizes_unsqueeze_view_4]
Unsloth: Compiling kernels: 100%|██████████| 3/3 [00:00<00:00, 15.69it/s, triton_red_fused__to_copy_add_mean_mul_pow_rsqrt_2]

INFO 09-04 11:43:54 [backends.py:282] Compiling a graph for dynamic shape takes 22.75 s
INFO 09-04 11:44:03 [monitor.py:34] torch.compile takes 36.29 s in total
INFO 09-04 11:45:45 [gpu_worker.py:359] Available KV cache memory: 7.60 GiB
INFO 09-04 11:45:46 [kv_cache_utils.py:1229] GPU KV cache size: 62,224 tokens
INFO 09-04 11:45:46 [kv_cache_utils.py:1234] Maximum concurrency for 512 tokens per request: 117.85x
INFO 09-04 11:45:46 [kernel_warmup.py:65] Warming up FlashInfer attention.
INFO 09-04 11:48:18 [vllm_utils.py:757] Unsloth: Running patched vLLM v1 `capture_model`.

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE):   0%|          | 0/22 [00:00<?, ?it/s]

WARNING 09-04 11:48:18 [utils.py:250] Using default LoRA kernel configs

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 22/22 [00:17<00:00,  1.27it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 14/14 [00:02<00:00,  6.47it/s]

INFO 09-04 11:48:38 [gpu_model_runner.py:4244] Graph capturing finished in 19 secs, took 0.38 GiB
INFO 09-04 11:48:38 [vllm_utils.py:764] Unsloth: Patched vLLM v1 graph capture finished in 19 secs.

INFO 09-04 11:48:39 [core.py:250] init engine (profile, create kv cache, warmup model) took 323.47 seconds
INFO 09-04 11:48:42 [llm.py:352] Supported tasks: ('generate',)

`torch_dtype` is deprecated! Use `dtype` instead!

Unsloth: Just some info: will skip parsing ['norm', 'post_feedforward_layernorm', 'ffn_norm', 'post_attention_layernorm', 'norm1', 'q_norm', 'layer_norm2', 'post_layernorm', 'pre_feedforward_layernorm', 'attention_norm', 'norm2', 'layer_norm1', 'k_norm', 'post_per_layer_input_norm', 'input_layernorm']
Performing substitution for additional_keys=set()
Unsloth: Just some info: will skip parsing ['norm', 'post_feedforward_layernorm', 'ffn_norm', 'cross_attn_input_layernorm', 'cross_attn_post_attention_layernorm', 'post_attention_layernorm', 'norm1', 'q_norm', 'layer_norm2', 'post_layernorm', 'pre_feedforward_layernorm', 'attention_norm', 'norm2', 'layer_norm1', 'k_norm', 'post_per_layer_input_norm', 'input_layernorm']
Unsloth: Explicit target_modules are constrained by the finetune_(vision|language|attention|mlp) filters; adapters attach only where both select.

### Data Prep
<a name="Data"></a>

We directly leverage [@willccbb](https://gist.github.com/willccbb/4676755236bb08cab5f4e54a0475d6fb) for data prep and all reward functions. You are free to create your own!

In [4]:
import re
from datasets import load_dataset, Dataset

# Load and prep dataset
SYSTEM_PROMPT = """
Respond in the following format:
<reasoning>
...
</reasoning>
<answer>
...
</answer>
"""

XML_COT_FORMAT = """\
<reasoning>
{reasoning}
</reasoning>
<answer>
{answer}
</answer>
"""

def extract_xml_answer(text: str) -> str:
    answer = text.split("<answer>")[-1]
    answer = answer.split("</answer>")[0]
    return answer.strip()

def extract_hash_answer(text: str) -> str | None:
    if "####" not in text:
        return None
    return text.split("####")[1].strip()

# uncomment middle messages for 1-shot prompting
def get_gsm8k_questions(split = "train") -> Dataset:
    data = load_dataset('openai/gsm8k', 'main')[split] # type: ignore
    data = data.map(lambda x: { # type: ignore
        'prompt': [
            {'role': 'system', 'content': SYSTEM_PROMPT},
            {'role': 'user', 'content': x['question']}
        ],
        'answer': extract_hash_answer(x['answer'])
    }) # type: ignore
    return data # type: ignore

dataset = get_gsm8k_questions()

# Reward functions
def correctness_reward_func(prompts, completions, answer, **kwargs) -> list[float]:
    responses = [completion[0]['content'] for completion in completions]
    q = prompts[0][-1]['content']
    extracted_responses = [extract_xml_answer(r) for r in responses]
    print('-'*20, f"Question:\n{q}", f"\nAnswer:\n{answer[0]}", f"\nResponse:\n{responses[0]}", f"\nExtracted:\n{extracted_responses[0]}")
    return [2.0 if r == a else 0.0 for r, a in zip(extracted_responses, answer)]

def int_reward_func(completions, **kwargs) -> list[float]:
    responses = [completion[0]['content'] for completion in completions]
    extracted_responses = [extract_xml_answer(r) for r in responses]
    return [0.5 if r.isdigit() else 0.0 for r in extracted_responses]

def strict_format_reward_func(completions, **kwargs) -> list[float]:
    """Reward function that checks if the completion has a specific format."""
    pattern = r"^<reasoning>\n.*?\n</reasoning>\n<answer>\n.*?\n</answer>\n$"
    responses = [completion[0]["content"] for completion in completions]
    matches = [re.match(pattern, r) for r in responses]
    return [0.5 if match else 0.0 for match in matches]

def soft_format_reward_func(completions, **kwargs) -> list[float]:
    """Reward function that checks if the completion has a specific format."""
    pattern = r"<reasoning>.*?</reasoning>\s*<answer>.*?</answer>"
    responses = [completion[0]["content"] for completion in completions]
    matches = [re.match(pattern, r) for r in responses]
    return [0.5 if match else 0.0 for match in matches]

def count_xml(text) -> float:
    count = 0.0
    if text.count("<reasoning>\n") == 1:
        count += 0.125
    if text.count("\n</reasoning>\n") == 1:
        count += 0.125
    if text.count("\n<answer>\n") == 1:
        count += 0.125
        count -= len(text.split("\n</answer>\n")[-1])*0.001
    if text.count("\n</answer>") == 1:
        count += 0.125
        count -= (len(text.split("\n</answer>")[-1]) - 1)*0.001
    return count

def xmlcount_reward_func(completions, **kwargs) -> list[float]:
    contents = [completion[0]["content"] for completion in completions]
    return [count_xml(c) for c in contents]

README.md: 0.00B [00:00, ?B/s]

main/train-00000-of-00001.parquet:   0%|          | 0.00/2.31M [00:00<?, ?B/s]

main/test-00000-of-00001.parquet:   0%|          | 0.00/419k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/7473 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1319 [00:00<?, ? examples/s]

Map:   0%|          | 0/7473 [00:00<?, ? examples/s]

<a name="Train"></a>
### Train the model

Now set up GRPO Trainer and all configurations!

In [5]:
from trl import GRPOConfig, GRPOTrainer
training_args = GRPOConfig(
    use_vllm = True, # use vllm for fast inference!
    learning_rate = 5e-6,
    adam_beta1 = 0.9,
    adam_beta2 = 0.99,
    weight_decay = 0.001,
    warmup_ratio = 0.1,
    lr_scheduler_type = "cosine",
    optim = "paged_adamw_8bit",
    logging_steps = 1,
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 1, # Increase to 4 for smoother training
    num_generations = 6, # Decrease if out of memory
    max_prompt_length = 256,
    max_completion_length = 200,
    # num_train_epochs = 1, # Set to 1 for a full training run
    max_steps = 100,
    save_steps = 250,
    max_grad_norm = 0.1,
    report_to = "none", # Can use Weights & Biases
    output_dir = "outputs",
)

Unsloth: We now expect `per_device_train_batch_size` * `gradient_accumulation_steps` * `world_size` to be a multiple of `num_generations`.
We will change the batch size of 1 to the `num_generations` of 6

And let's run the trainer! If you scroll up, you'll see a table of rewards. The goal is to see the `reward` column increase!

You might have to wait 150 to 200 steps for any action. You'll probably get 0 reward for the first 100 steps. Please be patient!

| Step | Training Loss | reward    | reward_std | completion_length | kl       |
|------|---------------|-----------|------------|-------------------|----------|
| 1    | 0.000000      | 0.125000  | 0.000000   | 200.000000        | 0.000000 |
| 2    | 0.000000      | 0.072375  | 0.248112   | 200.000000        | 0.000000 |
| 3    | 0.000000      | -0.079000 | 0.163776   | 182.500000        | 0.000005 |

In [6]:
trainer = GRPOTrainer(
    model = model,
    processing_class = tokenizer,
    reward_funcs = [
        xmlcount_reward_func,
        soft_format_reward_func,
        strict_format_reward_func,
        int_reward_func,
        correctness_reward_func,
    ],
    args = training_args,
    train_dataset = dataset,
)
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 7,473 | Num Epochs = 1 | Total steps = 100
O^O/ \_/ \    Batch size per device = 6 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (6 x 1 x 1) = 6
 "-____-"     Trainable parameters = 5,767,168 of 3,841,788,928 (0.15% trained)

WARNING 09-04 11:48:52 [processor.py:246] vLLM has deprecated support for supporting different tokenizers for different LoRAs. By default, vLLM uses base model's tokenizer. If you are using a LoRA with its own tokenizer, consider specifying `--tokenizer [lora_path]` to use the LoRA tokenizer.
Unsloth: Will smartly offload gradients to save VRAM!
-------------------- Question:
A concert ticket costs $40. Mr. Benson bought 12 tickets and received a 5% discount for every ticket bought that exceeds 10. How much did Mr. Benson pay in all?
Answer:
476
Response:
<think>
Okay, so Mr. Benson bought 12 concert tickets, right? Each ticket normally costs $40. The problem says he got a 5% discount on every ticket he bought that exceeds 10. Hmm, let me break this down.

First, I need to figure out how many tickets qualified for the discount. Since the discount applies to tickets that exceed 10, and he bought 12, that means 12 minus 10 = 2 tickets get the discount. Wait, no, wait. Wait, the problem says "a 5% discount for every ticket bought that exceeds 10." So, does that mean for each ticket beyond the 10th, he gets a 5% discount? So if he bought 12 tickets, the first 10 are at full price, and the next 2 are at a 5% discount?

Let me confirm that. So total tickets: 12. The discount applies to tickets over 10, so tickets
Extracted:
<think>
Okay, so Mr. Benson bought 12 concert tickets, right? Each ticket normally costs $40. The problem says he got a 5% discount on every ticket he bought that exceeds 10. Hmm, let me break this down.

First, I need to figure out how many tickets qualified for the discount. Since the discount applies to tickets that exceed 10, and he bought 12, that means 12 minus 10 = 2 tickets get the discount. Wait, no, wait. Wait, the problem says "a 5% discount for every ticket bought that exceeds 10." So, does that mean for each ticket beyond the 10th, he gets a 5% discount? So if he bought 12 tickets, the first 10 are at full price, and the next 2 are at a 5% discount?

Let me confirm that. So total tickets: 12. The discount applies to tickets over 10, so tickets

Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.
-------------------- Question:
Jane is trying to decide whether to buy a house or a trailer. A house costs $480,000 and a trailer costs $120,000. Each loan will be paid in monthly installments over 20 years. How much more is the monthly payment on the house compared to the trailer?
Answer:
1500
Response:
<think>
Okay, let's see. Jane is deciding between buying a house or a trailer, and she wants to know how much more the monthly payment for the house is compared to the trailer. The house costs $480,000 and the trailer is $120,000. Both loans are to be paid over 20 years. So, I need to calculate the monthly payments for both and then find the difference.

First, I remember that when you take out a loan, the monthly payments are calculated using an amortization formula. Since both loans are over 20 years, the loan term is the same. The key here is that the loan amounts are different, but the loan terms are the same. So, the monthly payments depend on the principal, the loan term, and the interest rate. Wait, but the problem doesn't mention an interest rate. Hmm, that's confusing. If there's no interest, then the monthly payments would just be the principal divided by the number of months. But usually
Extracted:
<think>
Okay, let's see. Jane is deciding between buying a house or a trailer, and she wants to know how much more the monthly payment for the house is compared to the trailer. The house costs $480,000 and the trailer is $120,000. Both loans are to be paid over 20 years. So, I need to calculate the monthly payments for both and then find the difference.

First, I remember that when you take out a loan, the monthly payments are calculated using an amortization formula. Since both loans are over 20 years, the loan term is the same. The key here is that the loan amounts are different, but the loan terms are the same. So, the monthly payments depend on the principal, the loan term, and the interest rate. Wait, but the problem doesn't mention an interest rate. Hmm, that's confusing. If there's no interest, then the monthly payments would just be the principal divided by the number of months. But usually
-------------------- Question:
Janet pays $40/hour for 3 hours per week of clarinet lessons and $28/hour for 5 hours a week of piano lessons. How much more does she spend on piano lessons than clarinet lessons in a year?
Answer:
1040
Response:
<think>
Okay, let herself into this problem. So, Janet is taking clarinet and piano lessons, and the question is asking how much more she spends on piano lessons compared to clarinet lessons in a year. Let me break this down step by step.

First, let's figure out the weekly cost for each type of lesson. For clarinet lessons, she pays $40 per hour, and she spends 3 hours each week. So, multiplying those together: 40 times 3. Let me do that math. 40 times 3 is 120. So, $120 per week on clarinet.

Then, for piano lessons, it's $28 per hour, and she attends for 5 hours a week. So, 28 multiplied by 5. Let me calculate that. 28 times 5... 28 times 5 is 140. That means $140 per week on piano lessons.

Now, the problem asks how much more she spends on piano than clar
Extracted:
<think>
Okay, let herself into this problem. So, Janet is taking clarinet and piano lessons, and the question is asking how much more she spends on piano lessons compared to clarinet lessons in a year. Let me break this down step by step.

First, let's figure out the weekly cost for each type of lesson. For clarinet lessons, she pays $40 per hour, and she spends 3 hours each week. So, multiplying those together: 40 times 3. Let me do that math. 40 times 3 is 120. So, $120 per week on clarinet.

Then, for piano lessons, it's $28 per hour, and she attends for 5 hours a week. So, 28 multiplied by 5. Let me calculate that. 28 times 5... 28 times 5 is 140. That means $140 per week on piano lessons.

Now, the problem asks how much more she spends on piano than clar
-------------------- Question:
Sabrina is collecting herbs to make a poultice for her grandmother. She needs twice as many basil leaves as sage leaves and 5 fewer sage leaves than verbena leaves. If she needs 12 basil leaves, how many leaves total does she need?
Answer:
29
Response:
<think>
Okay, let's see. Sabrina needs to collect herbs for a poultice. The problem says she needs twice as many basil leaves as sage leaves and 5 fewer sage leaves than verbena leaves. If she needs 12 basil leaves, what's the total number of leaves she needs? Hmm, let apart the information step by step.

First, let's list out the relationships. The key points are:

1. Basil leaves are twice the number of sage leaves.
2. Sage leaves are five fewer than verbena leaves.
3. Basil leaves needed are 12.

So, starting with basil. Since basil is twice sage, we can write that as:

Basil = 2 * Sage

We know Basil is 12, so plugging that in:

12 = 2 * Sage

To find Sage, divide both sides by 2:

Sage = 12 / 2 = 6

So, she needs 6 sage leaves. Now, the next relationship is that
Extracted:
<think>
Okay, let's see. Sabrina needs to collect herbs for a poultice. The problem says she needs twice as many basil leaves as sage leaves and 5 fewer sage leaves than verbena leaves. If she needs 12 basil leaves, what's the total number of leaves she needs? Hmm, let apart the information step by step.

First, let's list out the relationships. The key points are:

1. Basil leaves are twice the number of sage leaves.
2. Sage leaves are five fewer than verbena leaves.
3. Basil leaves needed are 12.

So, starting with basil. Since basil is twice sage, we can write that as:

Basil = 2 * Sage

We know Basil is 12, so plugging that in:

12 = 2 * Sage

To find Sage, divide both sides by 2:

Sage = 12 / 2 = 6

So, she needs 6 sage leaves. Now, the next relationship is that
-------------------- Question:
Over the past five years, on July 4th, the high temperature for Washington, DC has been: 90 degrees in 2020, 90 degrees in 2019, 90 degrees in 2018, 79 degrees in 2017 and 71 degrees in 2016. What is the average temperature for July 4th in Washington, DC over the past 5 years?
Answer:
84
Response:
<think>
Okay, let's see. The user is asking for the average temperature on July 4th in Washington, DC over the past five years. The temperatures given are 90, 90, 90, 79, and 71 degrees for the years 2020 to 2017 respectively. Wait, hold on, the years are listed from 2020 down to 2016, so that's five years' worth of data. To find the average, I need to add all those temperatures together and then divide by the number of years, which is 5.

First, let me confirm the temperatures: 90, 90, 90, 79, 71. Adding them up step by step. Let's start with the first three: 90 + 90 = 180, then 180 + 90 = 270. Then add 79: 270 + 79 = 349. Then add 71: 349 + 71 =
Extracted:
<think>
Okay, let's see. The user is asking for the average temperature on July 4th in Washington, DC over the past five years. The temperatures given are 90, 90, 90, 79, and 71 degrees for the years 2020 to 2017 respectively. Wait, hold on, the years are listed from 2020 down to 2016, so that's five years' worth of data. To find the average, I need to add all those temperatures together and then divide by the number of years, which is 5.

First, let me confirm the temperatures: 90, 90, 90, 79, 71. Adding them up step by step. Let's start with the first three: 90 + 90 = 180, then 180 + 90 = 270. Then add 79: 270 + 79 = 349. Then add 71: 349 + 71 =
-------------------- Question:
Rene can finish reading 30 pages in 60 minutes. Lulu can read 27 pages in 60 minutes and Cherry can read 25 pages in 60 minutes. If they have been reading for 240 minutes now, how many pages have they finished reading in total?
Answer:
328
Response:
<think>
Okay, let's see here. The problem is about Rene, Lulu, and Cherry reading pages over a certain time, and we need to find out how many pages they've read in total after 240 minutes. Alcompan, let me break this down step by step.

First, each of them has a different reading speed. Rene can read 30 pages in 60 minutes, Lulu 27 pages, and Cherry 25 pages. The time they've been reading is 240 minutes. Hmm, so I need to calculate how many pages each person reads in 240 minutes and then add them all together.

Let me start with Rene. If she can read 30 pages in 60 minutes, that's her rate. So, 60 minutes is 1 hour. Now, 240 minutes is how many hours? Let me convert that. Since 60 minutes is 1 hour, 240 divided by 60 is 4. So, 240 minutes is 4 hours. That
Extracted:
<think>
Okay, let's see here. The problem is about Rene, Lulu, and Cherry reading pages over a certain time, and we need to find out how many pages they've read in total after 240 minutes. Alcompan, let me break this down step by step.

First, each of them has a different reading speed. Rene can read 30 pages in 60 minutes, Lulu 27 pages, and Cherry 25 pages. The time they've been reading is 240 minutes. Hmm, so I need to calculate how many pages each person reads in 240 minutes and then add them all together.

Let me start with Rene. If she can read 30 pages in 60 minutes, that's her rate. So, 60 minutes is 1 hour. Now, 240 minutes is how many hours? Let me convert that. Since 60 minutes is 1 hour, 240 divided by 60 is 4. So, 240 minutes is 4 hours. That
-------------------- Question:
Martin rings the small bell 4 times more than 1/3 as often as the big bell. If he rings both of them a combined total of 52 times, how many times does he ring the big bell?
Answer:
36
Response:
<think>
Okay, let's see here. Martin rings the small bell 4 times more than 1/3 as often as the big bell. The total combined rings are 52. I need to find how many times he rings the big bell. Hmm, let me break this down.

First, let me parse the problem statement carefully. The small bell is rung 4 times more than 1/3 as often as the big bell. That wording is a bit tricky. Let me rephrase it: The number of times the small bell is rung is equal to 1/3 of the number of times the big bell is rung plus 4 more. So, if B is the number of times the big bell is rung, then the small bell S is (1/3)B + 4. Is that correct? Let me check again. The problem says "4 times more than 1/3 as often as the big bell." Wait, maybe the wording is "
Extracted:
<think>
Okay, let's see here. Martin rings the small bell 4 times more than 1/3 as often as the big bell. The total combined rings are 52. I need to find how many times he rings the big bell. Hmm, let me break this down.

First, let me parse the problem statement carefully. The small bell is rung 4 times more than 1/3 as often as the big bell. That wording is a bit tricky. Let me rephrase it: The number of times the small bell is rung is equal to 1/3 of the number of times the big bell is rung plus 4 more. So, if B is the number of times the big bell is rung, then the small bell S is (1/3)B + 4. Is that correct? Let me check again. The problem says "4 times more than 1/3 as often as the big bell." Wait, maybe the wording is "
-------------------- Question:
Bert fills out the daily crossword puzzle in the newspaper every day. He uses up a pencil to fill out the puzzles every two weeks. On average, it takes him 1050 words to use up a pencil. How many words are in each crossword puzzle on average?
Answer:
75
Response:
<think>
Okay, let's see. Bert uses up a pencil every two weeks by filling out daily crossword puzzles. It takes him an average of 1050 words to use up a pencil. The question is asking how many words are in each crossword puzzle on average. Hmm, so I need to figure out the number of words per puzzle based on the information given.

First, let frost understand the problem. Bert uses a pencil until it's done every two weeks. In those two weeks, he writes 1050 words total. Each day he does a crossword puzzle, and each puzzle has a certain number of words. So, over two weeks, which is 14 days, he does 14 crossword puzzles. The total words he writes with one pencil is 1050, so if I can find out how many words each puzzle has, that would answer the question.

Wait, but how exactly is the 1050 words counted? Is it the total number of words he writes with the pencil
Extracted:
<think>
Okay, let's see. Bert uses up a pencil every two weeks by filling out daily crossword puzzles. It takes him an average of 1050 words to use up a pencil. The question is asking how many words are in each crossword puzzle on average. Hmm, so I need to figure out the number of words per puzzle based on the information given.

First, let frost understand the problem. Bert uses a pencil until it's done every two weeks. In those two weeks, he writes 1050 words total. Each day he does a crossword puzzle, and each puzzle has a certain number of words. So, over two weeks, which is 14 days, he does 14 crossword puzzles. The total words he writes with one pencil is 1050, so if I can find out how many words each puzzle has, that would answer the question.

Wait, but how exactly is the 1050 words counted? Is it the total number of words he writes with the pencil
-------------------- Question:
Matt can make a batch of a dozen cookies using 2 pounds of flour.  He uses 4 bags of flour each weighing 5 pounds.  If Jim eats 15 cookies how many cookies are left?
Answer:
105
Response:
<think>
Okay, let's see. So the problem is about Matt making cookies and then Jim eating some, and we need to figure out how many cookies are left. Al-bas-al, right? Let me break this down step by step.

First, Matt can make a batch of a dozen cookies using 2 pounds of flour. A dozen is 12 cookies. So, 2 pounds of flour = 12 cookies. Got that. Now, he uses 4 bags of flour, each weighing 5 pounds. So, each bag is 5 pounds, and there are 4 bags. Let me calculate the total amount of flour he has.

4 bags * 5 pounds per bag = 20 pounds of flour total. Okay, so he has 20 pounds of flour. Now, since he uses 2 pounds per dozen cookies, how many batches can he make? Wait, or maybe how many cookies can he make in total?

Let me think. If 2 pounds makes
Extracted:
<think>
Okay, let's see. So the problem is about Matt making cookies and then Jim eating some, and we need to figure out how many cookies are left. Al-bas-al, right? Let me break this down step by step.

First, Matt can make a batch of a dozen cookies using 2 pounds of flour. A dozen is 12 cookies. So, 2 pounds of flour = 12 cookies. Got that. Now, he uses 4 bags of flour, each weighing 5 pounds. So, each bag is 5 pounds, and there are 4 bags. Let me calculate the total amount of flour he has.

4 bags * 5 pounds per bag = 20 pounds of flour total. Okay, so he has 20 pounds of flour. Now, since he uses 2 pounds per dozen cookies, how many batches can he make? Wait, or maybe how many cookies can he make in total?

Let me think. If 2 pounds makes
-------------------- Question:
James decides to build a tin house by collecting 500 tins in a week. On the first day, he collects 50 tins. On the second day, he manages to collect 3 times that number. On the third day, he collects 50 tins fewer than the number he collected on the second day. If he collects an equal number of tins on the remaining days of the week, what's the number of tins he collected each day for the rest of the week?
Answer:
50
Response:
<think>
Okay, let me try to figure out this problem step by step. So, James wants to build a tin house and he needs 500 tins in a week. He starts collecting them over seven days. The problem gives me the number of tins he collects on the first three days, and then says he collects an equal number each day for the remaining days. I need to find out how many tins he collects each of those remaining days.

First, let's break down the information given. On the first day, he collects 50 tins. That's straightforward. Then, on the second day, he collects three times the number he got on the first day. Three times 50 would be 150 tins. So day one: 50, day two: 150.

On the third day, he collects 50 tins fewer than on the second day. So, if day two was 150, then day three would be 150 minus 50, which is 100
Extracted:
<think>
Okay, let me try to figure out this problem step by step. So, James wants to build a tin house and he needs 500 tins in a week. He starts collecting them over seven days. The problem gives me the number of tins he collects on the first three days, and then says he collects an equal number each day for the remaining days. I need to find out how many tins he collects each of those remaining days.

First, let's break down the information given. On the first day, he collects 50 tins. That's straightforward. Then, on the second day, he collects three times the number he got on the first day. Three times 50 would be 150 tins. So day one: 50, day two: 150.

On the third day, he collects 50 tins fewer than on the second day. So, if day two was 150, then day three would be 150 minus 50, which is 100
-------------------- Question:
A jar of jellybeans has 14 blue jellybeans, 26 purple jellybeans and 40 orange jellybeans. If there are 200 jellybeans in the jar, how many are there of the red color?
Answer:
120
Response:
<think>
Okay, let's see. So, the problem is about a jar of jellybeans with different colors: blue, purple, orange, and red. The total number of jellybeans is 200. They've given the numbers for blue, purple, and orange, and we need to find out how many are red. Alvin, um, wait, the user's name is Phi, right? Anyway, the task is to calculate the number of red jellybeans.

First, let me make sure I understand the problem correctly. The jar contains 14 blue, 26 purple, 40 orange, and an unknown number of red ones. The total is 200. So, if I sum up all the known colors and subtract that from the total, the result should be the number of red jellybeans. That makes sense because the sum of all individual colors should equal the total number of jellybeans in the jar.

Let me break it down step by step. Let's add up the blue,
Extracted:
<think>
Okay, let's see. So, the problem is about a jar of jellybeans with different colors: blue, purple, orange, and red. The total number of jellybeans is 200. They've given the numbers for blue, purple, and orange, and we need to find out how many are red. Alvin, um, wait, the user's name is Phi, right? Anyway, the task is to calculate the number of red jellybeans.

First, let me make sure I understand the problem correctly. The jar contains 14 blue, 26 purple, 40 orange, and an unknown number of red ones. The total is 200. So, if I sum up all the known colors and subtract that from the total, the result should be the number of red jellybeans. That makes sense because the sum of all individual colors should equal the total number of jellybeans in the jar.

Let me break it down step by step. Let's add up the blue,
-------------------- Question:
Five adults and two children go to see a movie and buy $12 worth of concessions. The total cost of their trip is $76. If each child's ticket is $7, how much, in dollars, are the adult tickets?
Answer:
10
Response:
<think>
Okay, let's see. So the problem is about five adults and two children going to the movies and buying concessions. The total cost is $76, and each child's ticket is $7. They also spent $12 on concessions. I need to find out how much each adult ticket costs. Hmm, let me break this down step by step.

First, the total cost is $76. This includes the tickets for everyone and the concessions. The concessions are $12, so maybe I should subtract that first to find out how much was spent on tickets alone. Let me check that. If I take the total $76 minus the $12 concessions, that would give me $64 left for the tickets. Yeah, that makes sense.

Now, there are five adult tickets and two child tickets. Each child's ticket is $7, so I can calculate the total cost for the children's tickets first. Two children at $7 each would be 2 times 7, which is $14
Extracted:
<think>

-------------------- Question:
A salon has the same amount of customers every day. Each customer needs 1 can of hairspray during the styling and is also given 1 can of hairspray to take home. The salon also buys an extra 5 cans of hairspray each day to ensure there is never a shortage. If the salon buys 33 cans of hairspray every day, how many customers do they have each day?
Answer:
14
Response:
<think>
Okay, let's see. The problem is about a salon that has the same number of customers every day. Each customer uses 1 can of hairspray during styling and takes 1 can home. The salon also buys an extra 5 cans each day to prevent shortages. They've purchased 33 cans daily. We need to find out how many customers they have each day.

Hmm, let me break this down. So, every customer requires 2 cans: one during the styling and one to take home. So if there are, say, x customers, they would need 2x cans per day. Then, on top of that, the salon buys an extra 5 cans. So total cans bought each day would be 2x + 5. And we know that total is 33 cans. So the equation would be 2x + 5 = 33. Then solve for x.

Wait, let me check if that's correct. Each customer indeed uses
Extracted:
<think>
Okay, let's see. The problem is about a salon that has the same number of customers every day. Each customer uses 1 can of hairspray during styling and takes 1 can home. The salon also buys an extra 5 cans each day to prevent shortages. They've purchased 33 cans daily. We need to find out how many customers they have each day.

Hmm, let me break this down. So, every customer requires 2 cans: one during the styling and one to take home. So if there are, say, x customers, they would need 2x cans per day. Then, on top of that, the salon buys an extra 5 cans. So total cans bought each day would be 2x + 5. And we know that total is 33 cans. So the equation would be 2x + 5 = 33. Then solve for x.

Wait, let me check if that's correct. Each customer indeed uses
-------------------- Question:
Sandy earns $15 per hour. She worked 10 hours on Friday with her best friend, 6 hours on Saturday alone and 14 hours on Sunday with her other co-workers. How much money did Sandy earn in all on Friday, Saturday and Sunday?
Answer:
450
Response:
<think>
Okay, let's see. Sandy earns $15 per hour, right? The question is asking how much she earned in total on Friday, Saturday, and Sunday. So, first, I need to figure out how many hours she worked each day and then multiply that by her hourly rate.

On Friday, she worked 10 hours. But wait, the problem mentions she worked with her best friend. Hmm, does that affect her pay? Probably not, since the hourly rate is given regardless. So, 10 hours times $15 per hour. Let alone, 10 * 15 = $150 for Friday.

Then, on Saturday, she worked 6 hours alone. Again, working alone or with others doesn't change her hourly wage. So 6 hours * $15. Let me calculate that: 6 * 15 = $90 for Saturday.

On Sunday, she worked 14 hours with her co-workers. Same reasoning here; the co-workers are just additional people,
Extracted:
<think>
Okay, let's see. Sandy earns $15 per hour, right? The question is asking how much she earned in total on Friday, Saturday, and Sunday. So, first, I need to figure out how many hours she worked each day and then multiply that by her hourly rate.

On Friday, she worked 10 hours. But wait, the problem mentions she worked with her best friend. Hmm, does that affect her pay? Probably not, since the hourly rate is given regardless. So, 10 hours times $15 per hour. Let alone, 10 * 15 = $150 for Friday.

Then, on Saturday, she worked 6 hours alone. Again, working alone or with others doesn't change her hourly wage. So 6 hours * $15. Let me calculate that: 6 * 15 = $90 for Saturday.

On Sunday, she worked 14 hours with her co-workers. Same reasoning here; the co-workers are just additional people,
-------------------- Question:
Michael has $42. Michael gives away half the money to his brother. His brother then buys 3 dollars worth of candy. If his brother has $35 left, how much money, in dollars, did his brother have at first?
Answer:
17
Response:
<think>
Okay, let's see. So the problem is about Michael giving away money to his brother and then the brother spending some on candy, and we need to find out how much the brother had initially. Hmm. Let me break it down step by step.

First, Michael starts with $42 and he gives half to his brother. Half of $42 is $21, right? So Michael gives his brother $21. Then, the brother uses $3 of that to buy candy. After buying the candy, the brother has $35 left. So we need to figure out how much the brother had originally before receiving the $21 from Michael.

Wait, but the question is asking how much the brother had at first. So before receiving the $21 from Michael. But the problem states that Michael gives away half the money to his brother. Wait, does that mean Michael gives half of his own money to his brother, so Michael had $42, gives $21 to his brother, so
Extracted:
<think>
Okay, let's see. So the problem is about Michael giving away money to his brother and then the brother spending some on candy, and we need to find out how much the brother had initially. Hmm. Let me break it down step by step.

First, Michael starts with $42 and he gives half to his brother. Half of $42 is $21, right? So Michael gives his brother $21. Then, the brother uses $3 of that to buy candy. After buying the candy, the brother has $35 left. So we need to figure out how much the brother had originally before receiving the $21 from Michael.

Wait, but the question is asking how much the brother had at first. So before receiving the $21 from Michael. But the problem states that Michael gives away half the money to his brother. Wait, does that mean Michael gives half of his own money to his brother, so Michael had $42, gives $21 to his brother, so
-------------------- Question:
A convenience store sells 180  gallons of soda a week.  They buy syrup boxes that can make 30 gallons of soda, and each box costs $40.  How much do they pay for syrup a week?
Answer:
240
Response:
<think>
Okay, let aside look at the problem here. So, the convenience store sells 180 gallons of soda each week. They buy syrup boxes, each box can make 30 gallons of soda, and each box costs $40. The question is asking how much they pay for syrup in a week. Hmm, let's break this down step by step.

First, I need to figure out how many syrup boxes the store needs to buy each week to meet the demand of 180 gallons. Since each box makes 30 gallons, I think I should divide the total gallons needed by the number of gallons each box provides. So, 180 divided by 30. Let me check that. 30 times 6 is 180, so that would mean they need 6 boxes per week. Then, each box costs $40, so multiplying the number of boxes by the cost per box should give the total cost. So, 6 boxes times $40 each. 6 times
Extracted:
<think>
Okay, let aside look at the problem here. So, the convenience store sells 180 gallons of soda each week. They buy syrup boxes, each box can make 30 gallons of soda, and each box costs $40. The question is asking how much they pay for syrup in a week. Hmm, let's break this down step by step.

First, I need to figure out how many syrup boxes the store needs to buy each week to meet the demand of 180 gallons. Since each box makes 30 gallons, I think I should divide the total gallons needed by the number of gallons each box provides. So, 180 divided by 30. Let me check that. 30 times 6 is 180, so that would mean they need 6 boxes per week. Then, each box costs $40, so multiplying the number of boxes by the cost per box should give the total cost. So, 6 boxes times $40 each. 6 times
-------------------- Question:
The sum of the three numbers is 500. If the first number is 200, and the value of the second number is twice the value of the third number, find the value of the third number.
Answer:
100
Response:
<think>
Okay, let's see. The problem says that the sum of three numbers is 500. The first number is 200, and the second number is twice the third number. I need to find the value of the third number. Hmm, let me break this down step by step.

First, let me denote the three numbers. Let's call the first number A, the second number B, and the third number C. According to the problem, A is 200. So, A = 200. Then, the problem states that the second number is twice the third number. That means B = 2 * C. Also, the sum of the three numbers is 500, so A + B + C = 500.

Since I already know A is 200, I can substitute that into the equation. So, 200 + B + C = 500. Now, since B is twice C, I can replace B with 2C in the equation. That
Extracted:
<think>
Okay, let's see. The problem says that the sum of three numbers is 500. The first number is 200, and the second number is twice the third number. I need to find the value of the third number. Hmm, let me break this down step by step.

First, let me denote the three numbers. Let's call the first number A, the second number B, and the third number C. According to the problem, A is 200. So, A = 200. Then, the problem states that the second number is twice the third number. That means B = 2 * C. Also, the sum of the three numbers is 500, so A + B + C = 500.

Since I already know A is 200, I can substitute that into the equation. So, 200 + B + C = 500. Now, since B is twice C, I can replace B with 2C in the equation. That
-------------------- Question:
In the first round of bowling, Patrick knocked down a total of 70 pins and Richard knocked down 15 more pins than Patrick. In the second round, Patrick knocked down twice as many pins as Richard in the first round and Richard knocked down 3 less than Patrick. How many more pins in total did Richard knock down than Patrick?
Answer:
12
Response:
<think>
Okay, let's see. So, the problem is about Patrick and Richard knocking down pins in two rounds of bowling. We need to find out how many more pins Richard knocked down than Patrick in total. Hmm. Let me break this down step by step.

First, the first round: Patrick knocked down 70 pins. Richard knocked down 15 more pins than Patrick in the first round. So, for Richard's first round, it's Patrick's 70 plus 15. Let me write that down.

Richard's first round: 70 + 15 = 85 pins. Okay, that's straightforward.

Now, the second round. It says Patrick knocked down twice as many pins as Richard in the first round. Wait, so Patrick's second round is double Richard's first round. Richard's first round was 85, so Patrick's second round is 2 * 85. Let me calculate that.

Patrick's second round: 2 * 85 = 170 pins.
Extracted:
<think>
Okay, let's see. So, the problem is about Patrick and Richard knocking down pins in two rounds of bowling. We need to find out how many more pins Richard knocked down than Patrick in total. Hmm. Let me break this down step by step.

First, the first round: Patrick knocked down 70 pins. Richard knocked down 15 more pins than Patrick in the first round. So, for Richard's first round, it's Patrick's 70 plus 15. Let me write that down.

Richard's first round: 70 + 15 = 85 pins. Okay, that's straightforward.

Now, the second round. It says Patrick knocked down twice as many pins as Richard in the first round. Wait, so Patrick's second round is double Richard's first round. Richard's first round was 85, so Patrick's second round is 2 * 85. Let me calculate that.

Patrick's second round: 2 * 85 = 170 pins.
-------------------- Question:
Barry, Thomas and Emmanuel are to share a jar of 200 jelly beans. If Thomas takes 10%, and Barry and Emmanuel are to share the remainder in the ratio 4:5 respectively, how many jelly beans will Emmanuel get?
Answer:
100
Response:
<think>
Okay, let's see here. So, there are three people: Barry, Thomas, and Emmanuel, and they need to share a jar of 200 jelly beans. The problem is asking how many jelly beans Emmanuel will get. Let aside that part. Let me try to break this down step by step.

First, Thomas is taking 10% of the total jelly beans. The total number is 200. So, let me calculate how many Thomas takes. To find 10% of 200, I can convert 10% to a decimal, which is 0.10, and multiply that by 200. So, 0.10 times 200 equals 20. So Thomas takes 20 jelly beans. That leaves the remainder to be shared between Barry and Emmanuel. The remainder would be 200 minus 20, which is 180 jelly beans.

Now, Barry and Emmanuel are sharing these remaining 180 jelly beans in the ratio 4:5. Hmm
Extracted:
<think>
Okay, let's see here. So, there are three people: Barry, Thomas, and Emmanuel, and they need to share a jar of 200 jelly beans. The problem is asking how many jelly beans Emmanuel will get. Let aside that part. Let me try to break this down step by step.

First, Thomas is taking 10% of the total jelly beans. The total number is 200. So, let me calculate how many Thomas takes. To find 10% of 200, I can convert 10% to a decimal, which is 0.10, and multiply that by 200. So, 0.10 times 200 equals 20. So Thomas takes 20 jelly beans. That leaves the remainder to be shared between Barry and Emmanuel. The remainder would be 200 minus 20, which is 180 jelly beans.

Now, Barry and Emmanuel are sharing these remaining 180 jelly beans in the ratio 4:5. Hmm
-------------------- Question:
Libby has 160 quarters in her piggy bank. She has to pay $35 to replace her sister’s dress that she borrowed and ruined. After replacing the dress, how many quarters will Libby have left?
Answer:
20
Response:
<think>
Okay, let's see. Libby has 160 quarters, and she needs to pay $35 using those quarters. The question is how many quarters she'll have left after paying. Hmm.

First, I need to remember how much a quarter is worth. A quarter is $0.25, right? So each quarter is 25 cents. Now, she has 160 quarters. If each is 25 cents, then the total amount of money she has initially is 160 times $0.25. Let me calculate that.

Wait, but maybe there's a smarter way to do this without converting everything to dollars. Because the payment is in dollars, and the answer needs to be in quarters. Let me think. If she needs to pay $35, how many quarters makes $35? Since each dollar is 4 quarters, then $35 would be 35 times 4 quarters. Let me check that.

Yes, $1 equals 4 quarters, so $35
Extracted:
<think>
Okay, let's see. Libby has 160 quarters, and she needs to pay $35 using those quarters. The question is how many quarters she'll have left after paying. Hmm.

First, I need to remember how much a quarter is worth. A quarter is $0.25, right? So each quarter is 25 cents. Now, she has 160 quarters. If each is 25 cents, then the total amount of money she has initially is 160 times $0.25. Let me calculate that.

Wait, but maybe there's a smarter way to do this without converting everything to dollars. Because the payment is in dollars, and the answer needs to be in quarters. Let me think. If she needs to pay $35, how many quarters makes $35? Since each dollar is 4 quarters, then $35 would be 35 times 4 quarters. Let me check that.

Yes, $1 equals 4 quarters, so $35
-------------------- Question:
John has a very inefficient toilet that uses 5 gallons of water per flush and his household flushed 15 times per day.  He replaced it with a toilet that uses 80% less water per flush.  How much water did John save in June?
Answer:
1800
Response:
<think>
Okay, let's see. John had an old toilet that used 5 gallons per flush, and they flushed it 15 times a day. He replaced it with a new one that uses 80% less water. I need to figure out how much water he saved in June.

First, I should calculate the total water usage before and after replacing the toilet. Then subtract the two to find the savings. June has 30 days, right? So, days stayed the length same.

Original toilet: 5 gallons per flush. Flushes: 15 times a day. So daily usage was 5 * 15. Let me compute that. 5 times 15 is 75 gallons per day. Then for June, which is 30 days, the original usage would be 75 * 30. Let me do that multiplication. 75 * 30. 70*30 is 2100, and 5*30 is 150, so total 210
Extracted:
<think>
Okay, let's see. John had an old toilet that used 5 gallons per flush, and they flushed it 15 times a day. He replaced it with a new one that uses 80% less water. I need to figure out how much water he saved in June.

First, I should calculate the total water usage before and after replacing the toilet. Then subtract the two to find the savings. June has 30 days, right? So, days stayed the length same.

Original toilet: 5 gallons per flush. Flushes: 15 times a day. So daily usage was 5 * 15. Let me compute that. 5 times 15 is 75 gallons per day. Then for June, which is 30 days, the original usage would be 75 * 30. Let me do that multiplication. 75 * 30. 70*30 is 2100, and 5*30 is 150, so total 210
-------------------- Question:
Bill is making omelets for his family's breakfast. It takes him 3 minutes to chop a pepper, 4 minutes to chop an onion, and 1 minute to grate enough cheese for one omelet. It takes him 5 minutes to assemble and cook the omelet. If he needs to chop up four peppers, two onions, and also grates cheese for cooking each of five omelets, how long will he spend preparing for and cooking the five omelets?
Answer:
50
Response:
<think>
Okay, let alone try to figure out how long Bill will spend preparing and cooking the five omelets. Let's start by breaking down all the tasks he needs to do.

First, the problem says he needs to chop four peppers, two onions, and grate cheese for five omelets. Then he has to assemble and cook each omelet, which takes 5 minutes per omelet. But wait, I need to make sure I understand the timeline here. Is he preparing each ingredient separately and then cooking them all at once, or is he prepping each omelet one by one? Hmm, the question mentions "preparing for and cooking," so maybe he does all the chopping and grating first, then cooks the omelets. But let me check the problem again.

It says: "how long will he spend preparing for and cooking the five omelets?" So, preparing would involve chopping the peppers, onions, and grating the cheese, and then cooking each omelet.
Extracted:
<think>
Okay, let alone try to figure out how long Bill will spend preparing and cooking the five omelets. Let's start by breaking down all the tasks he needs to do.

First, the problem says he needs to chop four peppers, two onions, and grate cheese for five omelets. Then he has to assemble and cook each omelet, which takes 5 minutes per omelet. But wait, I need to make sure I understand the timeline here. Is he preparing each ingredient separately and then cooking them all at once, or is he prepping each omelet one by one? Hmm, the question mentions "preparing for and cooking," so maybe he does all the chopping and grating first, then cooks the omelets. But let me check the problem again.

It says: "how long will he spend preparing for and cooking the five omelets?" So, preparing would involve chopping the peppers, onions, and grating the cheese, and then cooking each omelet.
-------------------- Question:
Andy is a lawyer who's working on two lawsuits. The first lawsuit has a 30% chance of paying out $5,000,000 upon a win and $0 if he loses it. The second lawsuit has a 50% chance of paying out $1,000,000 if Andy loses and a 50% chance of paying out $2,000,000 if he wins.  Expressed as a percentage, how much more likely is it that Andy loses both lawsuits compared to winning both of them?
Answer:
20
Response:
<think>
Okay, let's see. So Andy is a lawyer working on two lawsuits. There are two lawsuits, each with different probabilities and payout amounts, but the question is about the likelihood of him losing both compared to winning both. Hmm. The question is asking how much more likely it is that he loses both lawsuits versus winning both, expressed as a percentage.

First, I need to figure out the probabilities of winning and losing each lawsuit separately. Let me start by parsing the information given for each lawsuit.


TrainOutput(global_step=100, training_loss=-0.0012199088387324863, metrics={'train_runtime': 2110.4803, 'train_samples_per_second': 0.284, 'train_steps_per_second': 0.047, 'total_flos': 0.0, 'train_loss': -0.0012199088387324863})

<a name="Inference"></a>
### Inference

Now let's try the model we just trained! First, let's first try the model without any GRPO trained:

In [7]:
text = tokenizer.apply_chat_template([
    {"role" : "user", "content" : "Which is bigger? 9.11 or 9.9?"},
], tokenize = False, add_generation_prompt = True)

from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 0.8,
    top_p = 0.95,
    max_tokens = 1024,
)
output = model.fast_generate(
    [text],
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

'<think>\nOkay, so I need to figure out which number is bigger between 9.11 and 9.9. Let me start by comparing the two numbers digit by digit. Both numbers have 9 in the units place, so that part is the same. Now, looking at the tenths place: 9.11 has 1 and 9.9 has 9. Wait, no, hold on. Let me write them down properly to avoid confusion.\n\n9.11 is nine and eleven hundredths, while 9.9 is nine and nine tenths. To compare them accurately, it might help to write 9.9 as 9.90 so both numbers have the same number of decimal places. So, 9.11 versus 9.90. \n\nStarting from the left, the units are both 9. Then, the tenths place: 1 vs. 9. Since 9 is larger than 1, 9.90 is bigger here. But wait, maybe I should check the hundredths place if the tenths differ. But since 1 is less than 9 in the tenths, 9.11 is definitely less than 9.9. Wait, no, 9.9 is the same as 9.90. So, 9.11 is 9 + 0.1 + 0.00, and 9.9 is 9 + 0.9. So, 0.9 is more than 0.1, so 9.9 is bigger. \n\nAlternatively, subtract them: 9.9 - 9.11 = 0.79, which is positive, so 9.9 is bigger. Or 9.11 - 9.9 = -0.09, so 9.9 is still bigger. Therefore, 9.9 is the larger number.\n</think>\n\nTo determine which number is larger between 9.11 and 9.9, we can compare them by aligning their decimal places:\n\n- **9.11** (written as 9.11)  \n- **9.9**  (written as 9.90 for clarity)  \n\n1. **Compare the units place**: Both have **9**.  \n2. **Compare the tenths place**:'

And now with the LoRA we just trained with GRPO - we first save the LoRA first!

In [8]:
model.save_lora("grpo_saved_lora")

Now we load the LoRA and test:

In [9]:
text = tokenizer.apply_chat_template([
    {"role" : "system", "content" : SYSTEM_PROMPT},
    {"role" : "user", "content" : "Which is bigger? 9.11 or 9.9?"},
], tokenize = False, add_generation_prompt = True)

from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 0.8,
    top_p = 0.95,
    max_tokens = 1024,
)
output = model.fast_generate(
    text,
    sampling_params = sampling_params,
    lora_request = model.load_lora("grpo_saved_lora"),
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

"<think>\nOkay, so I need to figure out which number is bigger between 9.11 and 9.9. Let me start by looking at the two numbers. Both are just under 10, but they have different decimal parts. \n\nFirst, I'll compare the whole number parts. Both are 9, so that doesn't help. Then, I look at the tenths place. The first number, 9.11, has 1 in the tenths place, while 9.9 has a 9. Wait, no, actually, 9.9 is the same as 9.90. So if I write them both with two decimal places, 9.11 vs. 9.90, it might be easier. \n\nNow, comparing the tenths place: 9.11 has 1 in the tenths place, and 9.90 has 9. Oh, wait, no! Wait, I think I got confused. Let me correct that. The first number is 9.11, so the whole number is 9, then the tenths place is 1, and the hundredths is 1. The second number, 9.9, is the same as 9.90. So the tenths place is 9, and the hundredths are 0. \n\nSo when comparing, the whole number is the same (9), so we look at the tenths. 9.11 has 1 in the tenths, and 9.9 has 9. Wait, that can't be right. Wait, no, 9.9 is 9 and 9 tenths, which is 9.90. So 9.11 is 9 units, 1 tenth, and 1 hundredth. 9.9 is 9 units, 9 tenths, and 0 hundredths. \n\nSo when comparing, the tenths place is 1 vs. 9. Since 9 tenths is more than 1 tenth, 9.9 is larger. Therefore, 9.11 is less than 9.9. Wait, that seems off. Wait, 9.9 is 9.90, and "

In [10]:
print(output)

<think>
Okay, so I need to figure out which number is bigger between 9.11 and 9.9. Let me start by looking at the two numbers. Both are just under 10, but they have different decimal parts.

First, I'll compare the whole number parts. Both are 9, so that doesn't help. Then, I look at the tenths place. The first number, 9.11, has 1 in the tenths place, while 9.9 has a 9. Wait, no, actually, 9.9 is the same as 9.90. So if I write them both with two decimal places, 9.11 vs. 9.90, it might be easier.

Now, comparing the tenths place: 9.11 has 1 in the tenths place, and 9.90 has 9. Oh, wait, no! Wait, I think I got confused. Let me correct that. The first number is 9.11, so the whole number is 9, then the tenths place is 1, and the hundredths is 1. The second number, 9.9, is the same as 9.90. So the tenths place is 9, and the hundredths are 0.

So when comparing, the whole number is the same (9), so we look at the tenths. 9.11 has 1 in the tenths, and 9.9 has 9. Wait, that can't be right. Wait, no, 9.9 is 9 and 9 tenths, which is 9.90. So 9.11 is 9 units, 1 tenth, and 1 hundredth. 9.9 is 9 units, 9 tenths, and 0 hundredths.

So when comparing, the tenths place is 1 vs. 9. Since 9 tenths is more than 1 tenth, 9.9 is larger. Therefore, 9.11 is less than 9.9. Wait, that seems off. Wait, 9.9 is 9.90, and

Our reasoning model is much better - it's not always correct, since we only trained it for an hour or so - it'll be better if we extend the sequence length and train for longer!

<a name="Save"></a>
### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens. See [our docs](https://unsloth.ai/docs/basics/inference-and-deployment) for more deployment options.

In [14]:
# Merge to 16bit
if True: model.save_pretrained_merged("phi_mini_finetune_16bit", tokenizer, save_method = "merged_16bit",)
if True: model.push_to_hub_merged("arefehRajabian/phi_mini_finetune_16bit", tokenizer, save_method = "merged_16bit", token = "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")

# Merge to 4bit
if False: model.save_pretrained_merged("phi_mini_finetune_4bit", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("arefehRajabian/phi_mini_finetune_4bit", tokenizer, save_method = "merged_4bit", token = "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")

# Just LoRA adapters
if False:
    model.save_pretrained("phi_lora")
    tokenizer.save_pretrained("phi_lora")
if False:
    model.push_to_hub("HF_USERNAME/phi_lora", token = "YOUR_HF_TOKEN")
    tokenizer.push_to_hub("HF_USERNAME/phi_lora", token = "YOUR_HF_TOKEN")

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub
Checking cache directory for required files...
Cache check failed: model-00001-of-00002.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.90G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files:  50%|█████     | 1/2 [02:28<02:28, 148.04s/it]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.77G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files: 100%|██████████| 2/2 [04:07<00:00, 123.85s/it]

Note: tokenizer.model not found (this is OK for non-SentencePiece models)

Unsloth: Merging weights into 16bit: 100%|██████████| 2/2 [04:00<00:00, 120.30s/it]

Unsloth: Merge process complete. Saved to `/content/phi_mini_finetune_16bit`

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...tune_16bit/tokenizer.json:  10%|#         | 1.63MB / 15.5MB

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub
Checking cache directory for required files...
Cache check failed: model-00001-of-00002.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.90G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files:  50%|█████     | 1/2 [02:50<02:50, 170.48s/it]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.77G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files: 100%|██████████| 2/2 [04:34<00:00, 137.02s/it]

Note: tokenizer.model not found (this is OK for non-SentencePiece models)

Unsloth: Merging weights into 16bit:   0%|          | 0/2 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...0001-of-00002.safetensors:   1%|          | 40.0MB / 4.90GB

Unsloth: Merging weights into 16bit:  50%|█████     | 1/2 [02:41<02:41, 161.93s/it]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...0002-of-00002.safetensors:   0%|          | 4.22MB / 2.77GB

Unsloth: Merging weights into 16bit: 100%|██████████| 2/2 [03:59<00:00, 119.79s/it]

Unsloth: Merge process complete. Saved to `/content/arefehRajabian/phi_mini_finetune_16bit`

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [docs page](https://unsloth.ai/docs/basics/inference-and-deployment/saving-to-gguf)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

[**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)

In [12]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("phi_finetune", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False: model.push_to_hub_gguf("HF_USERNAME/phi_finetune", tokenizer, token = "YOUR_HF_TOKEN")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("phi_finetune", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("HF_USERNAME/phi_finetune", tokenizer, quantization_method = "f16", token = "YOUR_HF_TOKEN")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("phi_finetune", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("HF_USERNAME/phi_finetune", tokenizer, quantization_method = "q4_k_m", token = "YOUR_HF_TOKEN")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "HF_USERNAME/phi_finetune", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "YOUR_HF_TOKEN",
    )

Now, use the `phi_finetune.Q8_0.gguf` file or `phi_finetune.Q4_K_M.gguf` file in llama.cpp.

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other resources:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
4. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://unsloth.ai/docs/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>

  This notebook and all Unsloth notebooks are licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).